//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from h:\source\home repos\sb\sblib\SB.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISBListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public partial class SBBaseListener : ISBListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>Dim</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDim([NotNull] SBParser.DimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Dim</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDim([NotNull] SBParser.DimContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Loc</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoc([NotNull] SBParser.LocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Loc</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoc([NotNull] SBParser.LocContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Implicit</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplicit([NotNull] SBParser.ImplicitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Implicit</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplicit([NotNull] SBParser.ImplicitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Reference</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReference([NotNull] SBParser.ReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Reference</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReference([NotNull] SBParser.ReferenceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Proc</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProc([NotNull] SBParser.ProcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Proc</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProc([NotNull] SBParser.ProcContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Func</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc([NotNull] SBParser.FuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Func</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc([NotNull] SBParser.FuncContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Longfor</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLongfor([NotNull] SBParser.LongforContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Longfor</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLongfor([NotNull] SBParser.LongforContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Shortfor</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShortfor([NotNull] SBParser.ShortforContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Shortfor</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShortfor([NotNull] SBParser.ShortforContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Shortrepeat</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShortrepeat([NotNull] SBParser.ShortrepeatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Shortrepeat</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShortrepeat([NotNull] SBParser.ShortrepeatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Longrepeat</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLongrepeat([NotNull] SBParser.LongrepeatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Longrepeat</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLongrepeat([NotNull] SBParser.LongrepeatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Shortif</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShortif([NotNull] SBParser.ShortifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Shortif</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShortif([NotNull] SBParser.ShortifContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Longif</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLongif([NotNull] SBParser.LongifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Longif</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLongif([NotNull] SBParser.LongifContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Longselect</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLongselect([NotNull] SBParser.LongselectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Longselect</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLongselect([NotNull] SBParser.LongselectContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Remark</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemark([NotNull] SBParser.RemarkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Remark</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemark([NotNull] SBParser.RemarkContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Onselect</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnselect([NotNull] SBParser.OnselectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Onselect</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnselect([NotNull] SBParser.OnselectContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Nextstmt</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNextstmt([NotNull] SBParser.NextstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Nextstmt</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNextstmt([NotNull] SBParser.NextstmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Exitstmt</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExitstmt([NotNull] SBParser.ExitstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Exitstmt</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExitstmt([NotNull] SBParser.ExitstmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] SBParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] SBParser.AssignmentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>IdentifierOnly</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierOnly([NotNull] SBParser.IdentifierOnlyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IdentifierOnly</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierOnly([NotNull] SBParser.IdentifierOnlyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Parenthesized</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesized([NotNull] SBParser.ParenthesizedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Parenthesized</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesized([NotNull] SBParser.ParenthesizedContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Binary</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary([NotNull] SBParser.BinaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Binary</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary([NotNull] SBParser.BinaryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Instr</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr([NotNull] SBParser.InstrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Instr</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr([NotNull] SBParser.InstrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot([NotNull] SBParser.NotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot([NotNull] SBParser.NotContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Term</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] SBParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Term</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] SBParser.TermContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] SBParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] SBParser.ProgramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] SBParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] SBParser.LineContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.stmtlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtlist([NotNull] SBParser.StmtlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.stmtlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtlist([NotNull] SBParser.StmtlistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] SBParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] SBParser.StmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.prochdr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProchdr([NotNull] SBParser.ProchdrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.prochdr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProchdr([NotNull] SBParser.ProchdrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.funchdr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunchdr([NotNull] SBParser.FunchdrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.funchdr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunchdr([NotNull] SBParser.FunchdrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] SBParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] SBParser.IdentifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.parenthesizedlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesizedlist([NotNull] SBParser.ParenthesizedlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.parenthesizedlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesizedlist([NotNull] SBParser.ParenthesizedlistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.unparenthesizedlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnparenthesizedlist([NotNull] SBParser.UnparenthesizedlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.unparenthesizedlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnparenthesizedlist([NotNull] SBParser.UnparenthesizedlistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.separator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparator([NotNull] SBParser.SeparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.separator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparator([NotNull] SBParser.SeparatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.constexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstexpr([NotNull] SBParser.ConstexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.constexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstexpr([NotNull] SBParser.ConstexprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.rangeexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRangeexpr([NotNull] SBParser.RangeexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.rangeexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRangeexpr([NotNull] SBParser.RangeexprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.terminator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminator([NotNull] SBParser.TerminatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.terminator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminator([NotNull] SBParser.TerminatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.lineNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineNumber([NotNull] SBParser.LineNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.lineNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineNumber([NotNull] SBParser.LineNumberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.endFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndFor([NotNull] SBParser.EndForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.endFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndFor([NotNull] SBParser.EndForContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.endDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndDef([NotNull] SBParser.EndDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.endDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndDef([NotNull] SBParser.EndDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.endRepeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndRepeat([NotNull] SBParser.EndRepeatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.endRepeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndRepeat([NotNull] SBParser.EndRepeatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.endIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndIf([NotNull] SBParser.EndIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.endIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndIf([NotNull] SBParser.EndIfContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.endSelect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndSelect([NotNull] SBParser.EndSelectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.endSelect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndSelect([NotNull] SBParser.EndSelectContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] SBParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] SBParser.ExprContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
