//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from h:\source\home repos\sb\sblib\SB.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SBParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public interface ISBListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>Dim</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDim([NotNull] SBParser.DimContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Dim</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDim([NotNull] SBParser.DimContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Loc</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoc([NotNull] SBParser.LocContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Loc</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoc([NotNull] SBParser.LocContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Implicit</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicit([NotNull] SBParser.ImplicitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Implicit</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicit([NotNull] SBParser.ImplicitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Reference</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReference([NotNull] SBParser.ReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Reference</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReference([NotNull] SBParser.ReferenceContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Proc</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProc([NotNull] SBParser.ProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Proc</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProc([NotNull] SBParser.ProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Func</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] SBParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Func</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] SBParser.FuncContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Longfor</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLongfor([NotNull] SBParser.LongforContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Longfor</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLongfor([NotNull] SBParser.LongforContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Shortfor</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortfor([NotNull] SBParser.ShortforContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Shortfor</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortfor([NotNull] SBParser.ShortforContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Shortrepeat</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortrepeat([NotNull] SBParser.ShortrepeatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Shortrepeat</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortrepeat([NotNull] SBParser.ShortrepeatContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Longrepeat</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLongrepeat([NotNull] SBParser.LongrepeatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Longrepeat</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLongrepeat([NotNull] SBParser.LongrepeatContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Shortif</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortif([NotNull] SBParser.ShortifContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Shortif</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortif([NotNull] SBParser.ShortifContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Longif</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLongif([NotNull] SBParser.LongifContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Longif</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLongif([NotNull] SBParser.LongifContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Longselect</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLongselect([NotNull] SBParser.LongselectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Longselect</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLongselect([NotNull] SBParser.LongselectContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Onselect</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnselect([NotNull] SBParser.OnselectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Onselect</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnselect([NotNull] SBParser.OnselectContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Nextstmt</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNextstmt([NotNull] SBParser.NextstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Nextstmt</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNextstmt([NotNull] SBParser.NextstmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Exitstmt</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExitstmt([NotNull] SBParser.ExitstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Exitstmt</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExitstmt([NotNull] SBParser.ExitstmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] SBParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] SBParser.AssignmentContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>IdentifierOnly</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierOnly([NotNull] SBParser.IdentifierOnlyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IdentifierOnly</c>
	/// labeled alternative in <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierOnly([NotNull] SBParser.IdentifierOnlyContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Procheader</c>
	/// labeled alternative in <see cref="SBParser.prochdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcheader([NotNull] SBParser.ProcheaderContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Procheader</c>
	/// labeled alternative in <see cref="SBParser.prochdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcheader([NotNull] SBParser.ProcheaderContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Funcheader</c>
	/// labeled alternative in <see cref="SBParser.funchdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncheader([NotNull] SBParser.FuncheaderContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Funcheader</c>
	/// labeled alternative in <see cref="SBParser.funchdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncheader([NotNull] SBParser.FuncheaderContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Parenthesizedl</c>
	/// labeled alternative in <see cref="SBParser.parenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedl([NotNull] SBParser.ParenthesizedlContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Parenthesizedl</c>
	/// labeled alternative in <see cref="SBParser.parenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedl([NotNull] SBParser.ParenthesizedlContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Unparenthesized</c>
	/// labeled alternative in <see cref="SBParser.unparenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnparenthesized([NotNull] SBParser.UnparenthesizedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Unparenthesized</c>
	/// labeled alternative in <see cref="SBParser.unparenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnparenthesized([NotNull] SBParser.UnparenthesizedContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Parenthesized</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesized([NotNull] SBParser.ParenthesizedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Parenthesized</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesized([NotNull] SBParser.ParenthesizedContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryAdditive</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryAdditive([NotNull] SBParser.UnaryAdditiveContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryAdditive</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryAdditive([NotNull] SBParser.UnaryAdditiveContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Binary</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary([NotNull] SBParser.BinaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Binary</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary([NotNull] SBParser.BinaryContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Instr</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr([NotNull] SBParser.InstrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Instr</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr([NotNull] SBParser.InstrContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot([NotNull] SBParser.NotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot([NotNull] SBParser.NotContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>Term</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] SBParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Term</c>
	/// labeled alternative in <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] SBParser.TermContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] SBParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] SBParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] SBParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] SBParser.LineContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.stmtlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtlist([NotNull] SBParser.StmtlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.stmtlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtlist([NotNull] SBParser.StmtlistContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.constexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstexpr([NotNull] SBParser.ConstexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.constexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstexpr([NotNull] SBParser.ConstexprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.rangeexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeexpr([NotNull] SBParser.RangeexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.rangeexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeexpr([NotNull] SBParser.RangeexprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] SBParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] SBParser.StmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.prochdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProchdr([NotNull] SBParser.ProchdrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.prochdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProchdr([NotNull] SBParser.ProchdrContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.funchdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunchdr([NotNull] SBParser.FunchdrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.funchdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunchdr([NotNull] SBParser.FunchdrContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.endDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndDef([NotNull] SBParser.EndDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.endDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndDef([NotNull] SBParser.EndDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] SBParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] SBParser.IdentifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.parenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedlist([NotNull] SBParser.ParenthesizedlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.parenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedlist([NotNull] SBParser.ParenthesizedlistContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.unparenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnparenthesizedlist([NotNull] SBParser.UnparenthesizedlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.unparenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnparenthesizedlist([NotNull] SBParser.UnparenthesizedlistContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.lineNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineNumber([NotNull] SBParser.LineNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.lineNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineNumber([NotNull] SBParser.LineNumberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.endFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndFor([NotNull] SBParser.EndForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.endFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndFor([NotNull] SBParser.EndForContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeparator([NotNull] SBParser.SeparatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeparator([NotNull] SBParser.SeparatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] SBParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] SBParser.ExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SBParser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminator([NotNull] SBParser.TerminatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SBParser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminator([NotNull] SBParser.TerminatorContext context);
}
