//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from h:\source\home repos\sb\sblib\SB.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public partial class SBParser : Parser {
	public const int
		Refer=1, Implic=2, Local=3, Dimension=4, DefProc=5, DefFunc=6, If=7, Else=8, 
		Then=9, EndIf=10, Select=11, EndSelect=12, EndDef=13, On=14, For=15, Next=16, 
		To=17, EndFor=18, Step=19, Repeat=20, Exit=21, Until=22, EndRepeat=23, 
		LeftParen=24, RightParen=25, LeftBracket=26, RightBracket=27, Equal=28, 
		NotEqual=29, Less=30, LessEqual=31, Greater=32, GreaterEqual=33, Plus=34, 
		Minus=35, Multiply=36, Divide=37, Mod=38, Div=39, And=40, Or=41, Xor=42, 
		Caret=43, Not=44, Tilde=45, Instr=46, Amp=47, Question=48, Colon=49, Semi=50, 
		Comma=51, Point=52, Bang=53, Whitespace=54, Newline=55, Let=56, Comment=57, 
		ID=58, Integer=59, Real=60, String=61, Unknowntype=62, Void=63;
	public const int
		RULE_program = 0, RULE_line = 1, RULE_stmtlist = 2, RULE_stmt = 3, RULE_prochdr = 4, 
		RULE_funchdr = 5, RULE_identifier = 6, RULE_parenthesizedlist = 7, RULE_unparenthesizedlist = 8, 
		RULE_separator = 9, RULE_constexpr = 10, RULE_rangeexpr = 11, RULE_terminator = 12, 
		RULE_lineNumber = 13, RULE_endFor = 14, RULE_endDef = 15, RULE_endRepeat = 16, 
		RULE_endIf = 17, RULE_endSelect = 18, RULE_expr = 19;
	public static readonly string[] ruleNames = {
		"program", "line", "stmtlist", "stmt", "prochdr", "funchdr", "identifier", 
		"parenthesizedlist", "unparenthesizedlist", "separator", "constexpr", 
		"rangeexpr", "terminator", "lineNumber", "endFor", "endDef", "endRepeat", 
		"endIf", "endSelect", "expr"
	};

	private static readonly string[] _LiteralNames = {
		null, "'REFERENCE'", null, "'LOCal'", "'DIM'", "'DEFine PROCedure'", "'DEFine FuNction'", 
		"'IF'", "'ELSE'", "'THEN'", "'END IF'", "'SELect ON'", "'END SELect'", 
		"'END DEFine'", "'ON'", "'FOR'", "'NEXT'", "'TO'", "'END FOR'", "'STEP'", 
		"'REPeat'", "'EXIT'", "'UNTIL'", "'END REPeat'", "'('", "')'", "'['", 
		"']'", "'='", "'<>'", "'<'", "'<='", "'>'", "'>='", "'+'", "'-'", "'*'", 
		"'/'", "'MOD'", "'DIV'", "'AND'", "'OR'", "'XOR'", "'^'", "'NOT'", "'~'", 
		"'INSTR'", "'&'", "'?'", "':'", "';'", "','", "'.'", "'!'", null, null, 
		"'LET'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Refer", "Implic", "Local", "Dimension", "DefProc", "DefFunc", "If", 
		"Else", "Then", "EndIf", "Select", "EndSelect", "EndDef", "On", "For", 
		"Next", "To", "EndFor", "Step", "Repeat", "Exit", "Until", "EndRepeat", 
		"LeftParen", "RightParen", "LeftBracket", "RightBracket", "Equal", "NotEqual", 
		"Less", "LessEqual", "Greater", "GreaterEqual", "Plus", "Minus", "Multiply", 
		"Divide", "Mod", "Div", "And", "Or", "Xor", "Caret", "Not", "Tilde", "Instr", 
		"Amp", "Question", "Colon", "Semi", "Comma", "Point", "Bang", "Whitespace", 
		"Newline", "Let", "Comment", "ID", "Integer", "Real", "String", "Unknowntype", 
		"Void"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete("Use IRecognizer.Vocabulary instead.")]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SB.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public SBParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class ProgramContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(SBParser.Eof, 0); }
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 40; line();
				}
				}
				State = 43;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Refer) | (1L << Implic) | (1L << Local) | (1L << Dimension) | (1L << DefProc) | (1L << DefFunc) | (1L << If) | (1L << Select) | (1L << On) | (1L << For) | (1L << Next) | (1L << Repeat) | (1L << Exit) | (1L << Newline) | (1L << Comment) | (1L << ID) | (1L << Integer))) != 0) );
			State = 45; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineContext : ParserRuleContext {
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public LineNumberContext lineNumber() {
			return GetRuleContext<LineNumberContext>(0);
		}
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public ITerminalNode Colon() { return GetToken(SBParser.Colon, 0); }
		public LineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_line; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLine(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLine(this);
		}
	}

	[RuleVersion(0)]
	public LineContext line() {
		LineContext _localctx = new LineContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_line);
		int _la;
		try {
			State = 58;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,3,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 48;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 47; lineNumber();
					}
				}

				State = 51;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Refer) | (1L << Implic) | (1L << Local) | (1L << Dimension) | (1L << DefProc) | (1L << DefFunc) | (1L << If) | (1L << Select) | (1L << On) | (1L << For) | (1L << Next) | (1L << Repeat) | (1L << Exit) | (1L << Comment) | (1L << ID))) != 0)) {
					{
					State = 50; stmtlist();
					}
				}

				State = 53; Match(Newline);
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 54; lineNumber();
				State = 55; Match(Colon);
				State = 56; Match(Newline);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtlistContext : ParserRuleContext {
		public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public StmtlistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmtlist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterStmtlist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitStmtlist(this);
		}
	}

	[RuleVersion(0)]
	public StmtlistContext stmtlist() {
		StmtlistContext _localctx = new StmtlistContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_stmtlist);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 60; stmt();
			State = 67;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,5,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 61; Match(Colon);
					State = 63;
					_errHandler.Sync(this);
					_la = _input.La(1);
					if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Refer) | (1L << Implic) | (1L << Local) | (1L << Dimension) | (1L << DefProc) | (1L << DefFunc) | (1L << If) | (1L << Select) | (1L << On) | (1L << For) | (1L << Next) | (1L << Repeat) | (1L << Exit) | (1L << Comment) | (1L << ID))) != 0)) {
						{
						State = 62; stmt();
						}
					}

					}
					} 
				}
				State = 69;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,5,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
	 
		public StmtContext() { }
		public virtual void CopyFrom(StmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DimContext : StmtContext {
		public ITerminalNode Dimension() { return GetToken(SBParser.Dimension, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ParenthesizedlistContext parenthesizedlist() {
			return GetRuleContext<ParenthesizedlistContext>(0);
		}
		public DimContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterDim(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitDim(this);
		}
	}
	public partial class LocContext : StmtContext {
		public ITerminalNode Local() { return GetToken(SBParser.Local, 0); }
		public UnparenthesizedlistContext unparenthesizedlist() {
			return GetRuleContext<UnparenthesizedlistContext>(0);
		}
		public LocContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLoc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLoc(this);
		}
	}
	public partial class ImplicitContext : StmtContext {
		public ITerminalNode Implic() { return GetToken(SBParser.Implic, 0); }
		public UnparenthesizedlistContext unparenthesizedlist() {
			return GetRuleContext<UnparenthesizedlistContext>(0);
		}
		public ImplicitContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterImplicit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitImplicit(this);
		}
	}
	public partial class ReferenceContext : StmtContext {
		public ITerminalNode Refer() { return GetToken(SBParser.Refer, 0); }
		public UnparenthesizedlistContext unparenthesizedlist() {
			return GetRuleContext<UnparenthesizedlistContext>(0);
		}
		public ReferenceContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterReference(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitReference(this);
		}
	}
	public partial class ProcContext : StmtContext {
		public ProchdrContext prochdr() {
			return GetRuleContext<ProchdrContext>(0);
		}
		public EndDefContext endDef() {
			return GetRuleContext<EndDefContext>(0);
		}
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public LineNumberContext lineNumber() {
			return GetRuleContext<LineNumberContext>(0);
		}
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ProcContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterProc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitProc(this);
		}
	}
	public partial class FuncContext : StmtContext {
		public FunchdrContext funchdr() {
			return GetRuleContext<FunchdrContext>(0);
		}
		public EndDefContext endDef() {
			return GetRuleContext<EndDefContext>(0);
		}
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public LineNumberContext lineNumber() {
			return GetRuleContext<LineNumberContext>(0);
		}
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public FuncContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterFunc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitFunc(this);
		}
	}
	public partial class LongforContext : StmtContext {
		public ITerminalNode For() { return GetToken(SBParser.For, 0); }
		public ITerminalNode[] ID() { return GetTokens(SBParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(SBParser.ID, i);
		}
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode To() { return GetToken(SBParser.To, 0); }
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public EndForContext endFor() {
			return GetRuleContext<EndForContext>(0);
		}
		public ITerminalNode Step() { return GetToken(SBParser.Step, 0); }
		public TerminatorContext terminator() {
			return GetRuleContext<TerminatorContext>(0);
		}
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public LineNumberContext lineNumber() {
			return GetRuleContext<LineNumberContext>(0);
		}
		public LongforContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLongfor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLongfor(this);
		}
	}
	public partial class ShortforContext : StmtContext {
		public ITerminalNode For() { return GetToken(SBParser.For, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode To() { return GetToken(SBParser.To, 0); }
		public ITerminalNode Colon() { return GetToken(SBParser.Colon, 0); }
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public ShortforContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterShortfor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitShortfor(this);
		}
	}
	public partial class ShortrepeatContext : StmtContext {
		public ITerminalNode Repeat() { return GetToken(SBParser.Repeat, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ITerminalNode Colon() { return GetToken(SBParser.Colon, 0); }
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public ShortrepeatContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterShortrepeat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitShortrepeat(this);
		}
	}
	public partial class LongrepeatContext : StmtContext {
		public ITerminalNode Repeat() { return GetToken(SBParser.Repeat, 0); }
		public ITerminalNode[] ID() { return GetTokens(SBParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(SBParser.ID, i);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public EndRepeatContext endRepeat() {
			return GetRuleContext<EndRepeatContext>(0);
		}
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public LineNumberContext lineNumber() {
			return GetRuleContext<LineNumberContext>(0);
		}
		public LongrepeatContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLongrepeat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLongrepeat(this);
		}
	}
	public partial class ShortifContext : StmtContext {
		public ITerminalNode If() { return GetToken(SBParser.If, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public StmtlistContext[] stmtlist() {
			return GetRuleContexts<StmtlistContext>();
		}
		public StmtlistContext stmtlist(int i) {
			return GetRuleContext<StmtlistContext>(i);
		}
		public ITerminalNode Then() { return GetToken(SBParser.Then, 0); }
		public ITerminalNode[] Colon() { return GetTokens(SBParser.Colon); }
		public ITerminalNode Colon(int i) {
			return GetToken(SBParser.Colon, i);
		}
		public ITerminalNode Else() { return GetToken(SBParser.Else, 0); }
		public ShortifContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterShortif(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitShortif(this);
		}
	}
	public partial class LongifContext : StmtContext {
		public ITerminalNode If() { return GetToken(SBParser.If, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public EndIfContext endIf() {
			return GetRuleContext<EndIfContext>(0);
		}
		public ITerminalNode Then() { return GetToken(SBParser.Then, 0); }
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ITerminalNode Else() { return GetToken(SBParser.Else, 0); }
		public LineNumberContext[] lineNumber() {
			return GetRuleContexts<LineNumberContext>();
		}
		public LineNumberContext lineNumber(int i) {
			return GetRuleContext<LineNumberContext>(i);
		}
		public LongifContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLongif(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLongif(this);
		}
	}
	public partial class LongselectContext : StmtContext {
		public ITerminalNode Select() { return GetToken(SBParser.Select, 0); }
		public ConstexprContext constexpr() {
			return GetRuleContext<ConstexprContext>(0);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public EndSelectContext endSelect() {
			return GetRuleContext<EndSelectContext>(0);
		}
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public LineNumberContext lineNumber() {
			return GetRuleContext<LineNumberContext>(0);
		}
		public LongselectContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLongselect(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLongselect(this);
		}
	}
	public partial class RemarkContext : StmtContext {
		public ITerminalNode Comment() { return GetToken(SBParser.Comment, 0); }
		public RemarkContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterRemark(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitRemark(this);
		}
	}
	public partial class OnselectContext : StmtContext {
		public ITerminalNode On() { return GetToken(SBParser.On, 0); }
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public RangeexprContext rangeexpr() {
			return GetRuleContext<RangeexprContext>(0);
		}
		public ConstexprContext constexpr() {
			return GetRuleContext<ConstexprContext>(0);
		}
		public OnselectContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterOnselect(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitOnselect(this);
		}
	}
	public partial class NextstmtContext : StmtContext {
		public ITerminalNode Next() { return GetToken(SBParser.Next, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public NextstmtContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterNextstmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitNextstmt(this);
		}
	}
	public partial class ExitstmtContext : StmtContext {
		public ITerminalNode Exit() { return GetToken(SBParser.Exit, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ExitstmtContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterExitstmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitExitstmt(this);
		}
	}
	public partial class AssignmentContext : StmtContext {
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssignmentContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_stmt);
		int _la;
		try {
			int _alt;
			State = 225;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,28,_ctx) ) {
			case 1:
				_localctx = new DimContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 70; Match(Dimension);
				State = 71; Match(ID);
				State = 72; parenthesizedlist();
				}
				break;

			case 2:
				_localctx = new LocContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 73; Match(Local);
				State = 74; unparenthesizedlist();
				}
				break;

			case 3:
				_localctx = new ImplicitContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 75; Match(Implic);
				State = 76; unparenthesizedlist();
				}
				break;

			case 4:
				_localctx = new ReferenceContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 77; Match(Refer);
				State = 78; unparenthesizedlist();
				}
				break;

			case 5:
				_localctx = new ProcContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 79; prochdr();
				State = 83;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 80; line();
						}
						} 
					}
					State = 85;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
				}
				State = 87;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 86; lineNumber();
					}
				}

				State = 89; endDef();
				State = 91;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 90; Match(ID);
					}
				}

				}
				break;

			case 6:
				_localctx = new FuncContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 93; funchdr();
				State = 97;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,9,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 94; line();
						}
						} 
					}
					State = 99;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,9,_ctx);
				}
				State = 101;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 100; lineNumber();
					}
				}

				State = 103; endDef();
				State = 105;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 104; Match(ID);
					}
				}

				}
				break;

			case 7:
				_localctx = new LongforContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 107; Match(For);
				State = 108; Match(ID);
				State = 109; Match(Equal);
				State = 110; expr(0);
				State = 111; Match(To);
				State = 112; expr(0);
				State = 115;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Step) {
					{
					State = 113; Match(Step);
					State = 114; terminator();
					}
				}

				State = 117; Match(Newline);
				State = 121;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,13,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 118; line();
						}
						} 
					}
					State = 123;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,13,_ctx);
				}
				State = 125;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 124; lineNumber();
					}
				}

				State = 127; endFor();
				State = 129;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 128; Match(ID);
					}
				}

				}
				break;

			case 8:
				_localctx = new ShortforContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 131; Match(For);
				State = 132; Match(ID);
				State = 133; Match(Equal);
				State = 134; expr(0);
				State = 135; Match(To);
				State = 136; expr(0);
				State = 137; Match(Colon);
				State = 138; stmtlist();
				}
				break;

			case 9:
				_localctx = new ShortrepeatContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 140; Match(Repeat);
				State = 141; Match(ID);
				State = 142; Match(Colon);
				State = 143; stmtlist();
				}
				break;

			case 10:
				_localctx = new LongrepeatContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 144; Match(Repeat);
				State = 145; Match(ID);
				State = 146; Match(Newline);
				State = 150;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,16,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 147; line();
						}
						} 
					}
					State = 152;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,16,_ctx);
				}
				State = 154;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 153; lineNumber();
					}
				}

				State = 156; endRepeat();
				State = 158;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 157; Match(ID);
					}
				}

				}
				break;

			case 11:
				_localctx = new ShortifContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 160; Match(If);
				State = 161; expr(0);
				State = 162;
				_la = _input.La(1);
				if ( !(_la==Then || _la==Colon) ) {
				_errHandler.RecoverInline(this);
				} else {
					if (_input.La(1) == TokenConstants.Eof) {
						matchedEOF = true;
					}

					_errHandler.ReportMatch(this);
					Consume();
				}
				State = 163; stmtlist();
				State = 168;
				_errHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(_input,19,_ctx) ) {
				case 1:
					{
					State = 164; Match(Colon);
					State = 165; Match(Else);
					State = 166; Match(Colon);
					State = 167; stmtlist();
					}
					break;
				}
				}
				break;

			case 12:
				_localctx = new LongifContext(_localctx);
				EnterOuterAlt(_localctx, 12);
				{
				State = 170; Match(If);
				State = 171; expr(0);
				State = 173;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Then) {
					{
					State = 172; Match(Then);
					}
				}

				State = 175; Match(Newline);
				State = 177;
				_errHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 176; line();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 179;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,21,_ctx);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
				State = 190;
				_errHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(_input,24,_ctx) ) {
				case 1:
					{
					State = 182;
					_errHandler.Sync(this);
					_la = _input.La(1);
					if (_la==Integer) {
						{
						State = 181; lineNumber();
						}
					}

					State = 184; Match(Else);
					State = 186;
					_errHandler.Sync(this);
					_alt = 1;
					do {
						switch (_alt) {
						case 1:
							{
							{
							State = 185; line();
							}
							}
							break;
						default:
							throw new NoViableAltException(this);
						}
						State = 188;
						_errHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(_input,23,_ctx);
					} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
					}
					break;
				}
				State = 193;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 192; lineNumber();
					}
				}

				State = 195; endIf();
				}
				break;

			case 13:
				_localctx = new LongselectContext(_localctx);
				EnterOuterAlt(_localctx, 13);
				{
				State = 197; Match(Select);
				State = 198; constexpr();
				State = 199; Match(Newline);
				State = 203;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,26,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 200; line();
						}
						} 
					}
					State = 205;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,26,_ctx);
				}
				State = 207;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 206; lineNumber();
					}
				}

				State = 209; endSelect();
				}
				break;

			case 14:
				_localctx = new RemarkContext(_localctx);
				EnterOuterAlt(_localctx, 14);
				{
				State = 211; Match(Comment);
				}
				break;

			case 15:
				_localctx = new OnselectContext(_localctx);
				EnterOuterAlt(_localctx, 15);
				{
				State = 212; Match(On);
				{
				State = 213; constexpr();
				}
				State = 214; Match(Equal);
				State = 215; rangeexpr();
				}
				break;

			case 16:
				_localctx = new NextstmtContext(_localctx);
				EnterOuterAlt(_localctx, 16);
				{
				State = 217; Match(Next);
				State = 218; Match(ID);
				}
				break;

			case 17:
				_localctx = new ExitstmtContext(_localctx);
				EnterOuterAlt(_localctx, 17);
				{
				State = 219; Match(Exit);
				State = 220; Match(ID);
				}
				break;

			case 18:
				_localctx = new AssignmentContext(_localctx);
				EnterOuterAlt(_localctx, 18);
				{
				State = 221; identifier();
				State = 222; Match(Equal);
				State = 223; expr(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ProchdrContext : ParserRuleContext {
		public ITerminalNode DefProc() { return GetToken(SBParser.DefProc, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ParenthesizedlistContext parenthesizedlist() {
			return GetRuleContext<ParenthesizedlistContext>(0);
		}
		public ProchdrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prochdr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterProchdr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitProchdr(this);
		}
	}

	[RuleVersion(0)]
	public ProchdrContext prochdr() {
		ProchdrContext _localctx = new ProchdrContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_prochdr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 227; Match(DefProc);
			State = 228; identifier();
			State = 230;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==LeftParen) {
				{
				State = 229; parenthesizedlist();
				}
			}

			State = 232; Match(Newline);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunchdrContext : ParserRuleContext {
		public ITerminalNode DefFunc() { return GetToken(SBParser.DefFunc, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ParenthesizedlistContext parenthesizedlist() {
			return GetRuleContext<ParenthesizedlistContext>(0);
		}
		public FunchdrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_funchdr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterFunchdr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitFunchdr(this);
		}
	}

	[RuleVersion(0)]
	public FunchdrContext funchdr() {
		FunchdrContext _localctx = new FunchdrContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_funchdr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 234; Match(DefFunc);
			State = 235; identifier();
			State = 237;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==LeftParen) {
				{
				State = 236; parenthesizedlist();
				}
			}

			State = 239; Match(Newline);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ParenthesizedlistContext parenthesizedlist() {
			return GetRuleContext<ParenthesizedlistContext>(0);
		}
		public UnparenthesizedlistContext unparenthesizedlist() {
			return GetRuleContext<UnparenthesizedlistContext>(0);
		}
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 241; Match(ID);
			State = 244;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,31,_ctx) ) {
			case 1:
				{
				State = 242; parenthesizedlist();
				}
				break;

			case 2:
				{
				State = 243; unparenthesizedlist();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParenthesizedlistContext : ParserRuleContext {
		public ITerminalNode LeftParen() { return GetToken(SBParser.LeftParen, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode RightParen() { return GetToken(SBParser.RightParen, 0); }
		public SeparatorContext[] separator() {
			return GetRuleContexts<SeparatorContext>();
		}
		public SeparatorContext separator(int i) {
			return GetRuleContext<SeparatorContext>(i);
		}
		public ParenthesizedlistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parenthesizedlist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterParenthesizedlist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitParenthesizedlist(this);
		}
	}

	[RuleVersion(0)]
	public ParenthesizedlistContext parenthesizedlist() {
		ParenthesizedlistContext _localctx = new ParenthesizedlistContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_parenthesizedlist);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 246; Match(LeftParen);
			State = 247; expr(0);
			State = 253;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << To) | (1L << Semi) | (1L << Comma) | (1L << Bang))) != 0)) {
				{
				{
				State = 248; separator();
				State = 249; expr(0);
				}
				}
				State = 255;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 256; Match(RightParen);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnparenthesizedlistContext : ParserRuleContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public SeparatorContext[] separator() {
			return GetRuleContexts<SeparatorContext>();
		}
		public SeparatorContext separator(int i) {
			return GetRuleContext<SeparatorContext>(i);
		}
		public UnparenthesizedlistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unparenthesizedlist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterUnparenthesizedlist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitUnparenthesizedlist(this);
		}
	}

	[RuleVersion(0)]
	public UnparenthesizedlistContext unparenthesizedlist() {
		UnparenthesizedlistContext _localctx = new UnparenthesizedlistContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_unparenthesizedlist);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 258; expr(0);
			State = 264;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,33,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 259; separator();
					State = 260; expr(0);
					}
					} 
				}
				State = 266;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,33,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SeparatorContext : ParserRuleContext {
		public ITerminalNode Comma() { return GetToken(SBParser.Comma, 0); }
		public ITerminalNode Bang() { return GetToken(SBParser.Bang, 0); }
		public ITerminalNode Semi() { return GetToken(SBParser.Semi, 0); }
		public ITerminalNode To() { return GetToken(SBParser.To, 0); }
		public SeparatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_separator; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterSeparator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitSeparator(this);
		}
	}

	[RuleVersion(0)]
	public SeparatorContext separator() {
		SeparatorContext _localctx = new SeparatorContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_separator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 267;
			_la = _input.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << To) | (1L << Semi) | (1L << Comma) | (1L << Bang))) != 0)) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstexprContext : ParserRuleContext {
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public ITerminalNode Real() { return GetToken(SBParser.Real, 0); }
		public ITerminalNode String() { return GetToken(SBParser.String, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ConstexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constexpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterConstexpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitConstexpr(this);
		}
	}

	[RuleVersion(0)]
	public ConstexprContext constexpr() {
		ConstexprContext _localctx = new ConstexprContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_constexpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 269;
			_la = _input.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << ID) | (1L << Integer) | (1L << Real) | (1L << String))) != 0)) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RangeexprContext : ParserRuleContext {
		public ConstexprContext[] constexpr() {
			return GetRuleContexts<ConstexprContext>();
		}
		public ConstexprContext constexpr(int i) {
			return GetRuleContext<ConstexprContext>(i);
		}
		public ITerminalNode To() { return GetToken(SBParser.To, 0); }
		public RangeexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rangeexpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterRangeexpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitRangeexpr(this);
		}
	}

	[RuleVersion(0)]
	public RangeexprContext rangeexpr() {
		RangeexprContext _localctx = new RangeexprContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_rangeexpr);
		try {
			State = 276;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,34,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 271; constexpr();
				State = 272; Match(To);
				State = 273; constexpr();
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 275; constexpr();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TerminatorContext : ParserRuleContext {
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public ITerminalNode String() { return GetToken(SBParser.String, 0); }
		public ITerminalNode Real() { return GetToken(SBParser.Real, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public TerminatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_terminator; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterTerminator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitTerminator(this);
		}
	}

	[RuleVersion(0)]
	public TerminatorContext terminator() {
		TerminatorContext _localctx = new TerminatorContext(_ctx, State);
		EnterRule(_localctx, 24, RULE_terminator);
		try {
			State = 282;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case Integer:
				EnterOuterAlt(_localctx, 1);
				{
				State = 278; Match(Integer);
				}
				break;
			case String:
				EnterOuterAlt(_localctx, 2);
				{
				State = 279; Match(String);
				}
				break;
			case Real:
				EnterOuterAlt(_localctx, 3);
				{
				State = 280; Match(Real);
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 4);
				{
				State = 281; identifier();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineNumberContext : ParserRuleContext {
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public LineNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lineNumber; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLineNumber(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLineNumber(this);
		}
	}

	[RuleVersion(0)]
	public LineNumberContext lineNumber() {
		LineNumberContext _localctx = new LineNumberContext(_ctx, State);
		EnterRule(_localctx, 26, RULE_lineNumber);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 284; Match(Integer);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndForContext : ParserRuleContext {
		public ITerminalNode EndFor() { return GetToken(SBParser.EndFor, 0); }
		public EndForContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_endFor; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterEndFor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitEndFor(this);
		}
	}

	[RuleVersion(0)]
	public EndForContext endFor() {
		EndForContext _localctx = new EndForContext(_ctx, State);
		EnterRule(_localctx, 28, RULE_endFor);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 286; Match(EndFor);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndDefContext : ParserRuleContext {
		public ITerminalNode EndDef() { return GetToken(SBParser.EndDef, 0); }
		public EndDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_endDef; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterEndDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitEndDef(this);
		}
	}

	[RuleVersion(0)]
	public EndDefContext endDef() {
		EndDefContext _localctx = new EndDefContext(_ctx, State);
		EnterRule(_localctx, 30, RULE_endDef);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 288; Match(EndDef);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndRepeatContext : ParserRuleContext {
		public ITerminalNode EndRepeat() { return GetToken(SBParser.EndRepeat, 0); }
		public EndRepeatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_endRepeat; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterEndRepeat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitEndRepeat(this);
		}
	}

	[RuleVersion(0)]
	public EndRepeatContext endRepeat() {
		EndRepeatContext _localctx = new EndRepeatContext(_ctx, State);
		EnterRule(_localctx, 32, RULE_endRepeat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 290; Match(EndRepeat);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndIfContext : ParserRuleContext {
		public ITerminalNode EndIf() { return GetToken(SBParser.EndIf, 0); }
		public EndIfContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_endIf; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterEndIf(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitEndIf(this);
		}
	}

	[RuleVersion(0)]
	public EndIfContext endIf() {
		EndIfContext _localctx = new EndIfContext(_ctx, State);
		EnterRule(_localctx, 34, RULE_endIf);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 292; Match(EndIf);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndSelectContext : ParserRuleContext {
		public ITerminalNode EndSelect() { return GetToken(SBParser.EndSelect, 0); }
		public EndSelectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_endSelect; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterEndSelect(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitEndSelect(this);
		}
	}

	[RuleVersion(0)]
	public EndSelectContext endSelect() {
		EndSelectContext _localctx = new EndSelectContext(_ctx, State);
		EnterRule(_localctx, 36, RULE_endSelect);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 294; Match(EndSelect);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParenthesizedContext : ExprContext {
		public ITerminalNode LeftParen() { return GetToken(SBParser.LeftParen, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode RightParen() { return GetToken(SBParser.RightParen, 0); }
		public ParenthesizedContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterParenthesized(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitParenthesized(this);
		}
	}
	public partial class UnaryAdditiveContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode Plus() { return GetToken(SBParser.Plus, 0); }
		public ITerminalNode Minus() { return GetToken(SBParser.Minus, 0); }
		public UnaryAdditiveContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterUnaryAdditive(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitUnaryAdditive(this);
		}
	}
	public partial class BinaryContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode Amp() { return GetToken(SBParser.Amp, 0); }
		public ITerminalNode Caret() { return GetToken(SBParser.Caret, 0); }
		public ITerminalNode Multiply() { return GetToken(SBParser.Multiply, 0); }
		public ITerminalNode Divide() { return GetToken(SBParser.Divide, 0); }
		public ITerminalNode Mod() { return GetToken(SBParser.Mod, 0); }
		public ITerminalNode Div() { return GetToken(SBParser.Div, 0); }
		public ITerminalNode Plus() { return GetToken(SBParser.Plus, 0); }
		public ITerminalNode Minus() { return GetToken(SBParser.Minus, 0); }
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public ITerminalNode NotEqual() { return GetToken(SBParser.NotEqual, 0); }
		public ITerminalNode Less() { return GetToken(SBParser.Less, 0); }
		public ITerminalNode LessEqual() { return GetToken(SBParser.LessEqual, 0); }
		public ITerminalNode Greater() { return GetToken(SBParser.Greater, 0); }
		public ITerminalNode GreaterEqual() { return GetToken(SBParser.GreaterEqual, 0); }
		public ITerminalNode And() { return GetToken(SBParser.And, 0); }
		public ITerminalNode Or() { return GetToken(SBParser.Or, 0); }
		public ITerminalNode Xor() { return GetToken(SBParser.Xor, 0); }
		public BinaryContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterBinary(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitBinary(this);
		}
	}
	public partial class InstrContext : ExprContext {
		public ITerminalNode Instr() { return GetToken(SBParser.Instr, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode String() { return GetToken(SBParser.String, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public InstrContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterInstr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitInstr(this);
		}
	}
	public partial class NotContext : ExprContext {
		public ITerminalNode Not() { return GetToken(SBParser.Not, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NotContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterNot(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitNot(this);
		}
	}
	public partial class TermContext : ExprContext {
		public TerminatorContext terminator() {
			return GetRuleContext<TerminatorContext>(0);
		}
		public TermContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterTerm(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitTerm(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(_ctx, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 38;
		EnterRecursionRule(_localctx, 38, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 309;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,36,_ctx) ) {
			case 1:
				{
				_localctx = new ParenthesizedContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;

				State = 297; Match(LeftParen);
				State = 298; expr(0);
				State = 299; Match(RightParen);
				}
				break;

			case 2:
				{
				_localctx = new UnaryAdditiveContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 301;
				_la = _input.La(1);
				if ( !(_la==Plus || _la==Minus) ) {
				_errHandler.RecoverInline(this);
				} else {
					if (_input.La(1) == TokenConstants.Eof) {
						matchedEOF = true;
					}

					_errHandler.ReportMatch(this);
					Consume();
				}
				State = 302; expr(11);
				}
				break;

			case 3:
				{
				_localctx = new InstrContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 303;
				_la = _input.La(1);
				if ( !(_la==ID || _la==String) ) {
				_errHandler.RecoverInline(this);
				} else {
					if (_input.La(1) == TokenConstants.Eof) {
						matchedEOF = true;
					}

					_errHandler.ReportMatch(this);
					Consume();
				}
				State = 304; Match(Instr);
				State = 305; expr(9);
				}
				break;

			case 4:
				{
				_localctx = new NotContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 306; Match(Not);
				State = 307; expr(4);
				}
				break;

			case 5:
				{
				_localctx = new TermContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 308; terminator();
				}
				break;
			}
			_ctx.stop = _input.Lt(-1);
			State = 334;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,38,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 332;
					_errHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(_input,37,_ctx) ) {
					case 1:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 311;
						if (!(Precpred(_ctx, 10))) throw new FailedPredicateException(this, "Precpred(_ctx, 10)");
						State = 312; Match(Amp);
						State = 313; expr(11);
						}
						break;

					case 2:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 314;
						if (!(Precpred(_ctx, 8))) throw new FailedPredicateException(this, "Precpred(_ctx, 8)");
						State = 315; Match(Caret);
						State = 316; expr(8);
						}
						break;

					case 3:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 317;
						if (!(Precpred(_ctx, 7))) throw new FailedPredicateException(this, "Precpred(_ctx, 7)");
						State = 318;
						_la = _input.La(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Multiply) | (1L << Divide) | (1L << Mod) | (1L << Div))) != 0)) ) {
						_errHandler.RecoverInline(this);
						} else {
							if (_input.La(1) == TokenConstants.Eof) {
								matchedEOF = true;
							}

							_errHandler.ReportMatch(this);
							Consume();
						}
						State = 319; expr(8);
						}
						break;

					case 4:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 320;
						if (!(Precpred(_ctx, 6))) throw new FailedPredicateException(this, "Precpred(_ctx, 6)");
						State = 321;
						_la = _input.La(1);
						if ( !(_la==Plus || _la==Minus) ) {
						_errHandler.RecoverInline(this);
						} else {
							if (_input.La(1) == TokenConstants.Eof) {
								matchedEOF = true;
							}

							_errHandler.ReportMatch(this);
							Consume();
						}
						State = 322; expr(7);
						}
						break;

					case 5:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 323;
						if (!(Precpred(_ctx, 5))) throw new FailedPredicateException(this, "Precpred(_ctx, 5)");
						State = 324;
						_la = _input.La(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Equal) | (1L << NotEqual) | (1L << Less) | (1L << LessEqual) | (1L << Greater) | (1L << GreaterEqual))) != 0)) ) {
						_errHandler.RecoverInline(this);
						} else {
							if (_input.La(1) == TokenConstants.Eof) {
								matchedEOF = true;
							}

							_errHandler.ReportMatch(this);
							Consume();
						}
						State = 325; expr(6);
						}
						break;

					case 6:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 326;
						if (!(Precpred(_ctx, 3))) throw new FailedPredicateException(this, "Precpred(_ctx, 3)");
						State = 327; Match(And);
						State = 328; expr(4);
						}
						break;

					case 7:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 329;
						if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
						State = 330;
						_la = _input.La(1);
						if ( !(_la==Or || _la==Xor) ) {
						_errHandler.RecoverInline(this);
						} else {
							if (_input.La(1) == TokenConstants.Eof) {
								matchedEOF = true;
							}

							_errHandler.ReportMatch(this);
							Consume();
						}
						State = 331; expr(3);
						}
						break;
					}
					} 
				}
				State = 336;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,38,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 19: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(_ctx, 10);

		case 1: return Precpred(_ctx, 8);

		case 2: return Precpred(_ctx, 7);

		case 3: return Precpred(_ctx, 6);

		case 4: return Precpred(_ctx, 5);

		case 5: return Precpred(_ctx, 3);

		case 6: return Precpred(_ctx, 2);
		}
		return true;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\x41\x154\x4\x2"+
		"\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4"+
		"\t\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10"+
		"\t\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x3\x2\x6\x2,\n\x2\r\x2\xE\x2-\x3\x2\x3\x2\x3\x3\x5\x3\x33\n\x3\x3\x3"+
		"\x5\x3\x36\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x5\x3=\n\x3\x3\x4\x3\x4"+
		"\x3\x4\x5\x4\x42\n\x4\a\x4\x44\n\x4\f\x4\xE\x4G\v\x4\x3\x5\x3\x5\x3\x5"+
		"\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\a\x5T\n\x5\f\x5\xE\x5"+
		"W\v\x5\x3\x5\x5\x5Z\n\x5\x3\x5\x3\x5\x5\x5^\n\x5\x3\x5\x3\x5\a\x5\x62"+
		"\n\x5\f\x5\xE\x5\x65\v\x5\x3\x5\x5\x5h\n\x5\x3\x5\x3\x5\x5\x5l\n\x5\x3"+
		"\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x5\x5v\n\x5\x3\x5\x3\x5"+
		"\a\x5z\n\x5\f\x5\xE\x5}\v\x5\x3\x5\x5\x5\x80\n\x5\x3\x5\x3\x5\x5\x5\x84"+
		"\n\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5"+
		"\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\a\x5\x97\n\x5\f\x5\xE\x5\x9A\v\x5"+
		"\x3\x5\x5\x5\x9D\n\x5\x3\x5\x3\x5\x5\x5\xA1\n\x5\x3\x5\x3\x5\x3\x5\x3"+
		"\x5\x3\x5\x3\x5\x3\x5\x3\x5\x5\x5\xAB\n\x5\x3\x5\x3\x5\x3\x5\x5\x5\xB0"+
		"\n\x5\x3\x5\x3\x5\x6\x5\xB4\n\x5\r\x5\xE\x5\xB5\x3\x5\x5\x5\xB9\n\x5\x3"+
		"\x5\x3\x5\x6\x5\xBD\n\x5\r\x5\xE\x5\xBE\x5\x5\xC1\n\x5\x3\x5\x5\x5\xC4"+
		"\n\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\a\x5\xCC\n\x5\f\x5\xE\x5\xCF"+
		"\v\x5\x3\x5\x5\x5\xD2\n\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3"+
		"\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x5\x5\xE4\n\x5\x3"+
		"\x6\x3\x6\x3\x6\x5\x6\xE9\n\x6\x3\x6\x3\x6\x3\a\x3\a\x3\a\x5\a\xF0\n\a"+
		"\x3\a\x3\a\x3\b\x3\b\x3\b\x5\b\xF7\n\b\x3\t\x3\t\x3\t\x3\t\x3\t\a\t\xFE"+
		"\n\t\f\t\xE\t\x101\v\t\x3\t\x3\t\x3\n\x3\n\x3\n\x3\n\a\n\x109\n\n\f\n"+
		"\xE\n\x10C\v\n\x3\v\x3\v\x3\f\x3\f\x3\r\x3\r\x3\r\x3\r\x3\r\x5\r\x117"+
		"\n\r\x3\xE\x3\xE\x3\xE\x3\xE\x5\xE\x11D\n\xE\x3\xF\x3\xF\x3\x10\x3\x10"+
		"\x3\x11\x3\x11\x3\x12\x3\x12\x3\x13\x3\x13\x3\x14\x3\x14\x3\x15\x3\x15"+
		"\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15"+
		"\x3\x15\x5\x15\x138\n\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3"+
		"\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3"+
		"\x15\x3\x15\x3\x15\x3\x15\x3\x15\a\x15\x14F\n\x15\f\x15\xE\x15\x152\v"+
		"\x15\x3\x15\x2\x2\x3(\x16\x2\x2\x4\x2\x6\x2\b\x2\n\x2\f\x2\xE\x2\x10\x2"+
		"\x12\x2\x14\x2\x16\x2\x18\x2\x1A\x2\x1C\x2\x1E\x2 \x2\"\x2$\x2&\x2(\x2"+
		"\x2\n\x4\x2\v\v\x33\x33\x5\x2\x13\x13\x34\x35\x37\x37\x3\x2<?\x3\x2$%"+
		"\x4\x2<<??\x3\x2&)\x3\x2\x1E#\x3\x2+,\x181\x2+\x3\x2\x2\x2\x4<\x3\x2\x2"+
		"\x2\x6>\x3\x2\x2\x2\b\xE3\x3\x2\x2\x2\n\xE5\x3\x2\x2\x2\f\xEC\x3\x2\x2"+
		"\x2\xE\xF3\x3\x2\x2\x2\x10\xF8\x3\x2\x2\x2\x12\x104\x3\x2\x2\x2\x14\x10D"+
		"\x3\x2\x2\x2\x16\x10F\x3\x2\x2\x2\x18\x116\x3\x2\x2\x2\x1A\x11C\x3\x2"+
		"\x2\x2\x1C\x11E\x3\x2\x2\x2\x1E\x120\x3\x2\x2\x2 \x122\x3\x2\x2\x2\"\x124"+
		"\x3\x2\x2\x2$\x126\x3\x2\x2\x2&\x128\x3\x2\x2\x2(\x137\x3\x2\x2\x2*,\x5"+
		"\x4\x3\x2+*\x3\x2\x2\x2,-\x3\x2\x2\x2-+\x3\x2\x2\x2-.\x3\x2\x2\x2./\x3"+
		"\x2\x2\x2/\x30\a\x2\x2\x3\x30\x3\x3\x2\x2\x2\x31\x33\x5\x1C\xF\x2\x32"+
		"\x31\x3\x2\x2\x2\x32\x33\x3\x2\x2\x2\x33\x35\x3\x2\x2\x2\x34\x36\x5\x6"+
		"\x4\x2\x35\x34\x3\x2\x2\x2\x35\x36\x3\x2\x2\x2\x36\x37\x3\x2\x2\x2\x37"+
		"=\a\x39\x2\x2\x38\x39\x5\x1C\xF\x2\x39:\a\x33\x2\x2:;\a\x39\x2\x2;=\x3"+
		"\x2\x2\x2<\x32\x3\x2\x2\x2<\x38\x3\x2\x2\x2=\x5\x3\x2\x2\x2>\x45\x5\b"+
		"\x5\x2?\x41\a\x33\x2\x2@\x42\x5\b\x5\x2\x41@\x3\x2\x2\x2\x41\x42\x3\x2"+
		"\x2\x2\x42\x44\x3\x2\x2\x2\x43?\x3\x2\x2\x2\x44G\x3\x2\x2\x2\x45\x43\x3"+
		"\x2\x2\x2\x45\x46\x3\x2\x2\x2\x46\a\x3\x2\x2\x2G\x45\x3\x2\x2\x2HI\a\x6"+
		"\x2\x2IJ\a<\x2\x2J\xE4\x5\x10\t\x2KL\a\x5\x2\x2L\xE4\x5\x12\n\x2MN\a\x4"+
		"\x2\x2N\xE4\x5\x12\n\x2OP\a\x3\x2\x2P\xE4\x5\x12\n\x2QU\x5\n\x6\x2RT\x5"+
		"\x4\x3\x2SR\x3\x2\x2\x2TW\x3\x2\x2\x2US\x3\x2\x2\x2UV\x3\x2\x2\x2VY\x3"+
		"\x2\x2\x2WU\x3\x2\x2\x2XZ\x5\x1C\xF\x2YX\x3\x2\x2\x2YZ\x3\x2\x2\x2Z[\x3"+
		"\x2\x2\x2[]\x5 \x11\x2\\^\a<\x2\x2]\\\x3\x2\x2\x2]^\x3\x2\x2\x2^\xE4\x3"+
		"\x2\x2\x2_\x63\x5\f\a\x2`\x62\x5\x4\x3\x2\x61`\x3\x2\x2\x2\x62\x65\x3"+
		"\x2\x2\x2\x63\x61\x3\x2\x2\x2\x63\x64\x3\x2\x2\x2\x64g\x3\x2\x2\x2\x65"+
		"\x63\x3\x2\x2\x2\x66h\x5\x1C\xF\x2g\x66\x3\x2\x2\x2gh\x3\x2\x2\x2hi\x3"+
		"\x2\x2\x2ik\x5 \x11\x2jl\a<\x2\x2kj\x3\x2\x2\x2kl\x3\x2\x2\x2l\xE4\x3"+
		"\x2\x2\x2mn\a\x11\x2\x2no\a<\x2\x2op\a\x1E\x2\x2pq\x5(\x15\x2qr\a\x13"+
		"\x2\x2ru\x5(\x15\x2st\a\x15\x2\x2tv\x5\x1A\xE\x2us\x3\x2\x2\x2uv\x3\x2"+
		"\x2\x2vw\x3\x2\x2\x2w{\a\x39\x2\x2xz\x5\x4\x3\x2yx\x3\x2\x2\x2z}\x3\x2"+
		"\x2\x2{y\x3\x2\x2\x2{|\x3\x2\x2\x2|\x7F\x3\x2\x2\x2}{\x3\x2\x2\x2~\x80"+
		"\x5\x1C\xF\x2\x7F~\x3\x2\x2\x2\x7F\x80\x3\x2\x2\x2\x80\x81\x3\x2\x2\x2"+
		"\x81\x83\x5\x1E\x10\x2\x82\x84\a<\x2\x2\x83\x82\x3\x2\x2\x2\x83\x84\x3"+
		"\x2\x2\x2\x84\xE4\x3\x2\x2\x2\x85\x86\a\x11\x2\x2\x86\x87\a<\x2\x2\x87"+
		"\x88\a\x1E\x2\x2\x88\x89\x5(\x15\x2\x89\x8A\a\x13\x2\x2\x8A\x8B\x5(\x15"+
		"\x2\x8B\x8C\a\x33\x2\x2\x8C\x8D\x5\x6\x4\x2\x8D\xE4\x3\x2\x2\x2\x8E\x8F"+
		"\a\x16\x2\x2\x8F\x90\a<\x2\x2\x90\x91\a\x33\x2\x2\x91\xE4\x5\x6\x4\x2"+
		"\x92\x93\a\x16\x2\x2\x93\x94\a<\x2\x2\x94\x98\a\x39\x2\x2\x95\x97\x5\x4"+
		"\x3\x2\x96\x95\x3\x2\x2\x2\x97\x9A\x3\x2\x2\x2\x98\x96\x3\x2\x2\x2\x98"+
		"\x99\x3\x2\x2\x2\x99\x9C\x3\x2\x2\x2\x9A\x98\x3\x2\x2\x2\x9B\x9D\x5\x1C"+
		"\xF\x2\x9C\x9B\x3\x2\x2\x2\x9C\x9D\x3\x2\x2\x2\x9D\x9E\x3\x2\x2\x2\x9E"+
		"\xA0\x5\"\x12\x2\x9F\xA1\a<\x2\x2\xA0\x9F\x3\x2\x2\x2\xA0\xA1\x3\x2\x2"+
		"\x2\xA1\xE4\x3\x2\x2\x2\xA2\xA3\a\t\x2\x2\xA3\xA4\x5(\x15\x2\xA4\xA5\t"+
		"\x2\x2\x2\xA5\xAA\x5\x6\x4\x2\xA6\xA7\a\x33\x2\x2\xA7\xA8\a\n\x2\x2\xA8"+
		"\xA9\a\x33\x2\x2\xA9\xAB\x5\x6\x4\x2\xAA\xA6\x3\x2\x2\x2\xAA\xAB\x3\x2"+
		"\x2\x2\xAB\xE4\x3\x2\x2\x2\xAC\xAD\a\t\x2\x2\xAD\xAF\x5(\x15\x2\xAE\xB0"+
		"\a\v\x2\x2\xAF\xAE\x3\x2\x2\x2\xAF\xB0\x3\x2\x2\x2\xB0\xB1\x3\x2\x2\x2"+
		"\xB1\xB3\a\x39\x2\x2\xB2\xB4\x5\x4\x3\x2\xB3\xB2\x3\x2\x2\x2\xB4\xB5\x3"+
		"\x2\x2\x2\xB5\xB3\x3\x2\x2\x2\xB5\xB6\x3\x2\x2\x2\xB6\xC0\x3\x2\x2\x2"+
		"\xB7\xB9\x5\x1C\xF\x2\xB8\xB7\x3\x2\x2\x2\xB8\xB9\x3\x2\x2\x2\xB9\xBA"+
		"\x3\x2\x2\x2\xBA\xBC\a\n\x2\x2\xBB\xBD\x5\x4\x3\x2\xBC\xBB\x3\x2\x2\x2"+
		"\xBD\xBE\x3\x2\x2\x2\xBE\xBC\x3\x2\x2\x2\xBE\xBF\x3\x2\x2\x2\xBF\xC1\x3"+
		"\x2\x2\x2\xC0\xB8\x3\x2\x2\x2\xC0\xC1\x3\x2\x2\x2\xC1\xC3\x3\x2\x2\x2"+
		"\xC2\xC4\x5\x1C\xF\x2\xC3\xC2\x3\x2\x2\x2\xC3\xC4\x3\x2\x2\x2\xC4\xC5"+
		"\x3\x2\x2\x2\xC5\xC6\x5$\x13\x2\xC6\xE4\x3\x2\x2\x2\xC7\xC8\a\r\x2\x2"+
		"\xC8\xC9\x5\x16\f\x2\xC9\xCD\a\x39\x2\x2\xCA\xCC\x5\x4\x3\x2\xCB\xCA\x3"+
		"\x2\x2\x2\xCC\xCF\x3\x2\x2\x2\xCD\xCB\x3\x2\x2\x2\xCD\xCE\x3\x2\x2\x2"+
		"\xCE\xD1\x3\x2\x2\x2\xCF\xCD\x3\x2\x2\x2\xD0\xD2\x5\x1C\xF\x2\xD1\xD0"+
		"\x3\x2\x2\x2\xD1\xD2\x3\x2\x2\x2\xD2\xD3\x3\x2\x2\x2\xD3\xD4\x5&\x14\x2"+
		"\xD4\xE4\x3\x2\x2\x2\xD5\xE4\a;\x2\x2\xD6\xD7\a\x10\x2\x2\xD7\xD8\x5\x16"+
		"\f\x2\xD8\xD9\a\x1E\x2\x2\xD9\xDA\x5\x18\r\x2\xDA\xE4\x3\x2\x2\x2\xDB"+
		"\xDC\a\x12\x2\x2\xDC\xE4\a<\x2\x2\xDD\xDE\a\x17\x2\x2\xDE\xE4\a<\x2\x2"+
		"\xDF\xE0\x5\xE\b\x2\xE0\xE1\a\x1E\x2\x2\xE1\xE2\x5(\x15\x2\xE2\xE4\x3"+
		"\x2\x2\x2\xE3H\x3\x2\x2\x2\xE3K\x3\x2\x2\x2\xE3M\x3\x2\x2\x2\xE3O\x3\x2"+
		"\x2\x2\xE3Q\x3\x2\x2\x2\xE3_\x3\x2\x2\x2\xE3m\x3\x2\x2\x2\xE3\x85\x3\x2"+
		"\x2\x2\xE3\x8E\x3\x2\x2\x2\xE3\x92\x3\x2\x2\x2\xE3\xA2\x3\x2\x2\x2\xE3"+
		"\xAC\x3\x2\x2\x2\xE3\xC7\x3\x2\x2\x2\xE3\xD5\x3\x2\x2\x2\xE3\xD6\x3\x2"+
		"\x2\x2\xE3\xDB\x3\x2\x2\x2\xE3\xDD\x3\x2\x2\x2\xE3\xDF\x3\x2\x2\x2\xE4"+
		"\t\x3\x2\x2\x2\xE5\xE6\a\a\x2\x2\xE6\xE8\x5\xE\b\x2\xE7\xE9\x5\x10\t\x2"+
		"\xE8\xE7\x3\x2\x2\x2\xE8\xE9\x3\x2\x2\x2\xE9\xEA\x3\x2\x2\x2\xEA\xEB\a"+
		"\x39\x2\x2\xEB\v\x3\x2\x2\x2\xEC\xED\a\b\x2\x2\xED\xEF\x5\xE\b\x2\xEE"+
		"\xF0\x5\x10\t\x2\xEF\xEE\x3\x2\x2\x2\xEF\xF0\x3\x2\x2\x2\xF0\xF1\x3\x2"+
		"\x2\x2\xF1\xF2\a\x39\x2\x2\xF2\r\x3\x2\x2\x2\xF3\xF6\a<\x2\x2\xF4\xF7"+
		"\x5\x10\t\x2\xF5\xF7\x5\x12\n\x2\xF6\xF4\x3\x2\x2\x2\xF6\xF5\x3\x2\x2"+
		"\x2\xF6\xF7\x3\x2\x2\x2\xF7\xF\x3\x2\x2\x2\xF8\xF9\a\x1A\x2\x2\xF9\xFF"+
		"\x5(\x15\x2\xFA\xFB\x5\x14\v\x2\xFB\xFC\x5(\x15\x2\xFC\xFE\x3\x2\x2\x2"+
		"\xFD\xFA\x3\x2\x2\x2\xFE\x101\x3\x2\x2\x2\xFF\xFD\x3\x2\x2\x2\xFF\x100"+
		"\x3\x2\x2\x2\x100\x102\x3\x2\x2\x2\x101\xFF\x3\x2\x2\x2\x102\x103\a\x1B"+
		"\x2\x2\x103\x11\x3\x2\x2\x2\x104\x10A\x5(\x15\x2\x105\x106\x5\x14\v\x2"+
		"\x106\x107\x5(\x15\x2\x107\x109\x3\x2\x2\x2\x108\x105\x3\x2\x2\x2\x109"+
		"\x10C\x3\x2\x2\x2\x10A\x108\x3\x2\x2\x2\x10A\x10B\x3\x2\x2\x2\x10B\x13"+
		"\x3\x2\x2\x2\x10C\x10A\x3\x2\x2\x2\x10D\x10E\t\x3\x2\x2\x10E\x15\x3\x2"+
		"\x2\x2\x10F\x110\t\x4\x2\x2\x110\x17\x3\x2\x2\x2\x111\x112\x5\x16\f\x2"+
		"\x112\x113\a\x13\x2\x2\x113\x114\x5\x16\f\x2\x114\x117\x3\x2\x2\x2\x115"+
		"\x117\x5\x16\f\x2\x116\x111\x3\x2\x2\x2\x116\x115\x3\x2\x2\x2\x117\x19"+
		"\x3\x2\x2\x2\x118\x11D\a=\x2\x2\x119\x11D\a?\x2\x2\x11A\x11D\a>\x2\x2"+
		"\x11B\x11D\x5\xE\b\x2\x11C\x118\x3\x2\x2\x2\x11C\x119\x3\x2\x2\x2\x11C"+
		"\x11A\x3\x2\x2\x2\x11C\x11B\x3\x2\x2\x2\x11D\x1B\x3\x2\x2\x2\x11E\x11F"+
		"\a=\x2\x2\x11F\x1D\x3\x2\x2\x2\x120\x121\a\x14\x2\x2\x121\x1F\x3\x2\x2"+
		"\x2\x122\x123\a\xF\x2\x2\x123!\x3\x2\x2\x2\x124\x125\a\x19\x2\x2\x125"+
		"#\x3\x2\x2\x2\x126\x127\a\f\x2\x2\x127%\x3\x2\x2\x2\x128\x129\a\xE\x2"+
		"\x2\x129\'\x3\x2\x2\x2\x12A\x12B\b\x15\x1\x2\x12B\x12C\a\x1A\x2\x2\x12C"+
		"\x12D\x5(\x15\x2\x12D\x12E\a\x1B\x2\x2\x12E\x138\x3\x2\x2\x2\x12F\x130"+
		"\t\x5\x2\x2\x130\x138\x5(\x15\r\x131\x132\t\x6\x2\x2\x132\x133\a\x30\x2"+
		"\x2\x133\x138\x5(\x15\v\x134\x135\a.\x2\x2\x135\x138\x5(\x15\x6\x136\x138"+
		"\x5\x1A\xE\x2\x137\x12A\x3\x2\x2\x2\x137\x12F\x3\x2\x2\x2\x137\x131\x3"+
		"\x2\x2\x2\x137\x134\x3\x2\x2\x2\x137\x136\x3\x2\x2\x2\x138\x150\x3\x2"+
		"\x2\x2\x139\x13A\f\f\x2\x2\x13A\x13B\a\x31\x2\x2\x13B\x14F\x5(\x15\r\x13C"+
		"\x13D\f\n\x2\x2\x13D\x13E\a-\x2\x2\x13E\x14F\x5(\x15\n\x13F\x140\f\t\x2"+
		"\x2\x140\x141\t\a\x2\x2\x141\x14F\x5(\x15\n\x142\x143\f\b\x2\x2\x143\x144"+
		"\t\x5\x2\x2\x144\x14F\x5(\x15\t\x145\x146\f\a\x2\x2\x146\x147\t\b\x2\x2"+
		"\x147\x14F\x5(\x15\b\x148\x149\f\x5\x2\x2\x149\x14A\a*\x2\x2\x14A\x14F"+
		"\x5(\x15\x6\x14B\x14C\f\x4\x2\x2\x14C\x14D\t\t\x2\x2\x14D\x14F\x5(\x15"+
		"\x5\x14E\x139\x3\x2\x2\x2\x14E\x13C\x3\x2\x2\x2\x14E\x13F\x3\x2\x2\x2"+
		"\x14E\x142\x3\x2\x2\x2\x14E\x145\x3\x2\x2\x2\x14E\x148\x3\x2\x2\x2\x14E"+
		"\x14B\x3\x2\x2\x2\x14F\x152\x3\x2\x2\x2\x150\x14E\x3\x2\x2\x2\x150\x151"+
		"\x3\x2\x2\x2\x151)\x3\x2\x2\x2\x152\x150\x3\x2\x2\x2)-\x32\x35<\x41\x45"+
		"UY]\x63gku{\x7F\x83\x98\x9C\xA0\xAA\xAF\xB5\xB8\xBE\xC0\xC3\xCD\xD1\xE3"+
		"\xE8\xEF\xF6\xFF\x10A\x116\x11C\x137\x14E\x150";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
