//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from h:\source\home repos\sb\sblib\SB.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public partial class SBParser : Parser {
	public const int
		Refer=1, Implic=2, Local=3, Dimension=4, DefProc=5, DefFunc=6, If=7, Else=8, 
		Then=9, EndIf=10, Select=11, EndSelect=12, EndDef=13, On=14, For=15, Next=16, 
		To=17, EndFor=18, Step=19, Repeat=20, Exit=21, Until=22, EndRepeat=23, 
		LeftParen=24, RightParen=25, LeftBracket=26, RightBracket=27, Equal=28, 
		NotEqual=29, Less=30, LessEqual=31, Greater=32, GreaterEqual=33, Plus=34, 
		Minus=35, Multiply=36, Divide=37, Mod=38, Div=39, And=40, Or=41, Xor=42, 
		Caret=43, Not=44, Tilde=45, Instr=46, Amp=47, Question=48, Colon=49, Semi=50, 
		Comma=51, Point=52, Bang=53, Whitespace=54, Let=55, Newline=56, String=57, 
		Comment=58, ID=59, Integer=60, Real=61, Unknowntype=62, Void=63, Scalar=64, 
		LineNumber=65;
	public const int
		RULE_program = 0, RULE_line = 1, RULE_stmtlist = 2, RULE_constexpr = 3, 
		RULE_rangeexpr = 4, RULE_stmt = 5, RULE_prochdr = 6, RULE_funchdr = 7, 
		RULE_endDef = 8, RULE_identifier = 9, RULE_parenthesizedlist = 10, RULE_unparenthesizedlist = 11, 
		RULE_separator = 12, RULE_expr = 13, RULE_terminator = 14;
	public static readonly string[] ruleNames = {
		"program", "line", "stmtlist", "constexpr", "rangeexpr", "stmt", "prochdr", 
		"funchdr", "endDef", "identifier", "parenthesizedlist", "unparenthesizedlist", 
		"separator", "expr", "terminator"
	};

	private static readonly string[] _LiteralNames = {
		null, "'REFERENCE'", null, "'LOCal'", "'DIM'", "'DEFine PROCedure'", "'DEFine FuNction'", 
		"'IF'", "'ELSE'", "'THEN'", "'END IF'", "'SELect ON'", "'END SELect'", 
		"'END DEFine'", "'ON'", "'FOR'", "'NEXT'", "'TO'", "'END FOR'", "'STEP'", 
		"'REPeat'", "'EXIT'", "'UNTIL'", "'END REPeat'", "'('", "')'", "'['", 
		"']'", "'='", "'<>'", "'<'", "'<='", "'>'", "'>='", "'+'", "'-'", "'*'", 
		"'/'", "'MOD'", "'DIV'", "'AND'", "'OR'", "'XOR'", "'^'", "'NOT'", "'~'", 
		"'INSTR'", "'&'", "'?'", "':'", "';'", "','", "'.'", "'!'", null, "'LET'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Refer", "Implic", "Local", "Dimension", "DefProc", "DefFunc", "If", 
		"Else", "Then", "EndIf", "Select", "EndSelect", "EndDef", "On", "For", 
		"Next", "To", "EndFor", "Step", "Repeat", "Exit", "Until", "EndRepeat", 
		"LeftParen", "RightParen", "LeftBracket", "RightBracket", "Equal", "NotEqual", 
		"Less", "LessEqual", "Greater", "GreaterEqual", "Plus", "Minus", "Multiply", 
		"Divide", "Mod", "Div", "And", "Or", "Xor", "Caret", "Not", "Tilde", "Instr", 
		"Amp", "Question", "Colon", "Semi", "Comma", "Point", "Bang", "Whitespace", 
		"Let", "Newline", "String", "Comment", "ID", "Integer", "Real", "Unknowntype", 
		"Void", "Scalar", "LineNumber"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete("Use IRecognizer.Vocabulary instead.")]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SB.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public SBParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class ProgramContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(SBParser.Eof, 0); }
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 31;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 30; line();
				}
				}
				State = 33;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Refer) | (1L << Implic) | (1L << Local) | (1L << Dimension) | (1L << DefProc) | (1L << DefFunc) | (1L << If) | (1L << Select) | (1L << On) | (1L << For) | (1L << Repeat) | (1L << Exit) | (1L << Newline) | (1L << ID) | (1L << Integer))) != 0) );
			State = 35; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineContext : ParserRuleContext {
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public ITerminalNode Colon() { return GetToken(SBParser.Colon, 0); }
		public LineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_line; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLine(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLine(this);
		}
	}

	[RuleVersion(0)]
	public LineContext line() {
		LineContext _localctx = new LineContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_line);
		int _la;
		try {
			State = 47;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,3,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 38;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 37; Match(Integer);
					}
				}

				State = 41;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Refer) | (1L << Implic) | (1L << Local) | (1L << Dimension) | (1L << DefProc) | (1L << DefFunc) | (1L << If) | (1L << Select) | (1L << On) | (1L << For) | (1L << Repeat) | (1L << Exit) | (1L << ID))) != 0)) {
					{
					State = 40; stmtlist();
					}
				}

				State = 43; Match(Newline);
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 44; Match(Integer);
				State = 45; Match(Colon);
				State = 46; Match(Newline);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtlistContext : ParserRuleContext {
		public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public StmtlistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmtlist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterStmtlist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitStmtlist(this);
		}
	}

	[RuleVersion(0)]
	public StmtlistContext stmtlist() {
		StmtlistContext _localctx = new StmtlistContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_stmtlist);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 49; stmt();
			State = 54;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,4,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 50; Match(Colon);
					State = 51; stmt();
					}
					} 
				}
				State = 56;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,4,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstexprContext : ParserRuleContext {
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public ITerminalNode Real() { return GetToken(SBParser.Real, 0); }
		public ITerminalNode String() { return GetToken(SBParser.String, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ConstexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constexpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterConstexpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitConstexpr(this);
		}
	}

	[RuleVersion(0)]
	public ConstexprContext constexpr() {
		ConstexprContext _localctx = new ConstexprContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_constexpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57;
			_la = _input.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << String) | (1L << ID) | (1L << Integer) | (1L << Real))) != 0)) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RangeexprContext : ParserRuleContext {
		public ConstexprContext[] constexpr() {
			return GetRuleContexts<ConstexprContext>();
		}
		public ConstexprContext constexpr(int i) {
			return GetRuleContext<ConstexprContext>(i);
		}
		public ITerminalNode To() { return GetToken(SBParser.To, 0); }
		public RangeexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rangeexpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterRangeexpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitRangeexpr(this);
		}
	}

	[RuleVersion(0)]
	public RangeexprContext rangeexpr() {
		RangeexprContext _localctx = new RangeexprContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_rangeexpr);
		try {
			State = 64;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,5,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 59; constexpr();
				State = 60; Match(To);
				State = 61; constexpr();
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 63; constexpr();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
	 
		public StmtContext() { }
		public virtual void CopyFrom(StmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DimContext : StmtContext {
		public ITerminalNode Dimension() { return GetToken(SBParser.Dimension, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ParenthesizedlistContext parenthesizedlist() {
			return GetRuleContext<ParenthesizedlistContext>(0);
		}
		public DimContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterDim(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitDim(this);
		}
	}
	public partial class LocContext : StmtContext {
		public ITerminalNode Local() { return GetToken(SBParser.Local, 0); }
		public UnparenthesizedlistContext unparenthesizedlist() {
			return GetRuleContext<UnparenthesizedlistContext>(0);
		}
		public LocContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLoc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLoc(this);
		}
	}
	public partial class ImplicitContext : StmtContext {
		public ITerminalNode Implic() { return GetToken(SBParser.Implic, 0); }
		public UnparenthesizedlistContext unparenthesizedlist() {
			return GetRuleContext<UnparenthesizedlistContext>(0);
		}
		public ImplicitContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterImplicit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitImplicit(this);
		}
	}
	public partial class ReferenceContext : StmtContext {
		public ITerminalNode Refer() { return GetToken(SBParser.Refer, 0); }
		public UnparenthesizedlistContext unparenthesizedlist() {
			return GetRuleContext<UnparenthesizedlistContext>(0);
		}
		public ReferenceContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterReference(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitReference(this);
		}
	}
	public partial class ProcContext : StmtContext {
		public ProchdrContext prochdr() {
			return GetRuleContext<ProchdrContext>(0);
		}
		public EndDefContext endDef() {
			return GetRuleContext<EndDefContext>(0);
		}
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ProcContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterProc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitProc(this);
		}
	}
	public partial class FuncContext : StmtContext {
		public FunchdrContext funchdr() {
			return GetRuleContext<FunchdrContext>(0);
		}
		public EndDefContext endDef() {
			return GetRuleContext<EndDefContext>(0);
		}
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public FuncContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterFunc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitFunc(this);
		}
	}
	public partial class LongforContext : StmtContext {
		public ITerminalNode For() { return GetToken(SBParser.For, 0); }
		public ITerminalNode[] ID() { return GetTokens(SBParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(SBParser.ID, i);
		}
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode To() { return GetToken(SBParser.To, 0); }
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ITerminalNode EndFor() { return GetToken(SBParser.EndFor, 0); }
		public ITerminalNode Step() { return GetToken(SBParser.Step, 0); }
		public TerminatorContext terminator() {
			return GetRuleContext<TerminatorContext>(0);
		}
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public LongforContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLongfor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLongfor(this);
		}
	}
	public partial class ShortforContext : StmtContext {
		public ITerminalNode For() { return GetToken(SBParser.For, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode To() { return GetToken(SBParser.To, 0); }
		public ITerminalNode Colon() { return GetToken(SBParser.Colon, 0); }
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public ShortforContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterShortfor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitShortfor(this);
		}
	}
	public partial class ShortrepeatContext : StmtContext {
		public ITerminalNode Repeat() { return GetToken(SBParser.Repeat, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ITerminalNode Colon() { return GetToken(SBParser.Colon, 0); }
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public ShortrepeatContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterShortrepeat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitShortrepeat(this);
		}
	}
	public partial class LongrepeatContext : StmtContext {
		public ITerminalNode Repeat() { return GetToken(SBParser.Repeat, 0); }
		public ITerminalNode[] ID() { return GetTokens(SBParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(SBParser.ID, i);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ITerminalNode EndRepeat() { return GetToken(SBParser.EndRepeat, 0); }
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public LongrepeatContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLongrepeat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLongrepeat(this);
		}
	}
	public partial class ShortifContext : StmtContext {
		public ITerminalNode If() { return GetToken(SBParser.If, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public StmtlistContext[] stmtlist() {
			return GetRuleContexts<StmtlistContext>();
		}
		public StmtlistContext stmtlist(int i) {
			return GetRuleContext<StmtlistContext>(i);
		}
		public ITerminalNode Then() { return GetToken(SBParser.Then, 0); }
		public ITerminalNode[] Colon() { return GetTokens(SBParser.Colon); }
		public ITerminalNode Colon(int i) {
			return GetToken(SBParser.Colon, i);
		}
		public ITerminalNode Else() { return GetToken(SBParser.Else, 0); }
		public ShortifContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterShortif(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitShortif(this);
		}
	}
	public partial class LongifContext : StmtContext {
		public ITerminalNode If() { return GetToken(SBParser.If, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ITerminalNode EndIf() { return GetToken(SBParser.EndIf, 0); }
		public ITerminalNode Then() { return GetToken(SBParser.Then, 0); }
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ITerminalNode Else() { return GetToken(SBParser.Else, 0); }
		public ITerminalNode[] Integer() { return GetTokens(SBParser.Integer); }
		public ITerminalNode Integer(int i) {
			return GetToken(SBParser.Integer, i);
		}
		public LongifContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLongif(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLongif(this);
		}
	}
	public partial class LongselectContext : StmtContext {
		public ITerminalNode Select() { return GetToken(SBParser.Select, 0); }
		public ConstexprContext constexpr() {
			return GetRuleContext<ConstexprContext>(0);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ITerminalNode EndSelect() { return GetToken(SBParser.EndSelect, 0); }
		public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public LongselectContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterLongselect(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitLongselect(this);
		}
	}
	public partial class OnselectContext : StmtContext {
		public ITerminalNode On() { return GetToken(SBParser.On, 0); }
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public RangeexprContext rangeexpr() {
			return GetRuleContext<RangeexprContext>(0);
		}
		public ConstexprContext constexpr() {
			return GetRuleContext<ConstexprContext>(0);
		}
		public OnselectContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterOnselect(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitOnselect(this);
		}
	}
	public partial class ExitstmtContext : StmtContext {
		public ITerminalNode Exit() { return GetToken(SBParser.Exit, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ExitstmtContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterExitstmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitExitstmt(this);
		}
	}
	public partial class AssignmentContext : StmtContext {
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssignmentContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
	}
	public partial class IdentifierOnlyContext : StmtContext {
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public IdentifierOnlyContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterIdentifierOnly(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitIdentifierOnly(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_stmt);
		int _la;
		try {
			int _alt;
			State = 221;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,29,_ctx) ) {
			case 1:
				_localctx = new DimContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 66; Match(Dimension);
				State = 67; Match(ID);
				State = 68; parenthesizedlist();
				}
				break;

			case 2:
				_localctx = new LocContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 69; Match(Local);
				State = 70; unparenthesizedlist();
				}
				break;

			case 3:
				_localctx = new ImplicitContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 71; Match(Implic);
				State = 72; unparenthesizedlist();
				}
				break;

			case 4:
				_localctx = new ReferenceContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 73; Match(Refer);
				State = 74; unparenthesizedlist();
				}
				break;

			case 5:
				_localctx = new ProcContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 75; prochdr();
				State = 79;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 76; line();
						}
						} 
					}
					State = 81;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
				}
				State = 83;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 82; Match(Integer);
					}
				}

				State = 85; endDef();
				State = 87;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 86; Match(ID);
					}
				}

				}
				break;

			case 6:
				_localctx = new FuncContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 89; funchdr();
				State = 93;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,9,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 90; line();
						}
						} 
					}
					State = 95;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,9,_ctx);
				}
				State = 97;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 96; Match(Integer);
					}
				}

				State = 99; endDef();
				State = 101;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 100; Match(ID);
					}
				}

				}
				break;

			case 7:
				_localctx = new LongforContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 103; Match(For);
				State = 104; Match(ID);
				State = 105; Match(Equal);
				State = 106; expr(0);
				State = 107; Match(To);
				State = 108; expr(0);
				State = 111;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Step) {
					{
					State = 109; Match(Step);
					State = 110; terminator();
					}
				}

				State = 113; Match(Newline);
				State = 117;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,13,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 114; line();
						}
						} 
					}
					State = 119;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,13,_ctx);
				}
				State = 121;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 120; Match(Integer);
					}
				}

				State = 123; Match(EndFor);
				State = 125;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 124; Match(ID);
					}
				}

				}
				break;

			case 8:
				_localctx = new ShortforContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 127; Match(For);
				State = 128; Match(ID);
				State = 129; Match(Equal);
				State = 130; expr(0);
				State = 131; Match(To);
				State = 132; expr(0);
				State = 133; Match(Colon);
				State = 134; stmtlist();
				}
				break;

			case 9:
				_localctx = new ShortrepeatContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 136; Match(Repeat);
				State = 137; Match(ID);
				State = 138; Match(Colon);
				State = 139; stmtlist();
				}
				break;

			case 10:
				_localctx = new LongrepeatContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 140; Match(Repeat);
				State = 141; Match(ID);
				State = 142; Match(Newline);
				State = 146;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,16,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 143; line();
						}
						} 
					}
					State = 148;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,16,_ctx);
				}
				State = 150;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 149; Match(Integer);
					}
				}

				{
				State = 152; Match(EndRepeat);
				State = 154;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 153; Match(ID);
					}
				}

				}
				}
				break;

			case 11:
				_localctx = new ShortifContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 156; Match(If);
				State = 157; expr(0);
				State = 158;
				_la = _input.La(1);
				if ( !(_la==Then || _la==Colon) ) {
				_errHandler.RecoverInline(this);
				} else {
					if (_input.La(1) == TokenConstants.Eof) {
						matchedEOF = true;
					}

					_errHandler.ReportMatch(this);
					Consume();
				}
				State = 159; stmtlist();
				State = 164;
				_errHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(_input,19,_ctx) ) {
				case 1:
					{
					State = 160; Match(Colon);
					State = 161; Match(Else);
					State = 162; Match(Colon);
					State = 163; stmtlist();
					}
					break;
				}
				}
				break;

			case 12:
				_localctx = new LongifContext(_localctx);
				EnterOuterAlt(_localctx, 12);
				{
				State = 166; Match(If);
				State = 167; expr(0);
				State = 169;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Then) {
					{
					State = 168; Match(Then);
					}
				}

				State = 171; Match(Newline);
				State = 173;
				_errHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 172; line();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 175;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,21,_ctx);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
				State = 186;
				_errHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(_input,24,_ctx) ) {
				case 1:
					{
					State = 178;
					_errHandler.Sync(this);
					_la = _input.La(1);
					if (_la==Integer) {
						{
						State = 177; Match(Integer);
						}
					}

					State = 180; Match(Else);
					State = 182;
					_errHandler.Sync(this);
					_alt = 1;
					do {
						switch (_alt) {
						case 1:
							{
							{
							State = 181; line();
							}
							}
							break;
						default:
							throw new NoViableAltException(this);
						}
						State = 184;
						_errHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(_input,23,_ctx);
					} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
					}
					break;
				}
				State = 189;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 188; Match(Integer);
					}
				}

				State = 191; Match(EndIf);
				}
				break;

			case 13:
				_localctx = new LongselectContext(_localctx);
				EnterOuterAlt(_localctx, 13);
				{
				State = 193; Match(Select);
				State = 194; constexpr();
				State = 195; Match(Newline);
				State = 199;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,26,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 196; line();
						}
						} 
					}
					State = 201;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,26,_ctx);
				}
				State = 203;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==Integer) {
					{
					State = 202; Match(Integer);
					}
				}

				State = 205; Match(EndSelect);
				}
				break;

			case 14:
				_localctx = new OnselectContext(_localctx);
				EnterOuterAlt(_localctx, 14);
				{
				State = 207; Match(On);
				{
				State = 208; constexpr();
				}
				State = 209; Match(Equal);
				State = 210; rangeexpr();
				}
				break;

			case 15:
				_localctx = new ExitstmtContext(_localctx);
				EnterOuterAlt(_localctx, 15);
				{
				State = 212; Match(Exit);
				State = 214;
				_errHandler.Sync(this);
				_la = _input.La(1);
				if (_la==ID) {
					{
					State = 213; Match(ID);
					}
				}

				}
				break;

			case 16:
				_localctx = new AssignmentContext(_localctx);
				EnterOuterAlt(_localctx, 16);
				{
				State = 216; identifier();
				State = 217; Match(Equal);
				State = 218; expr(0);
				}
				break;

			case 17:
				_localctx = new IdentifierOnlyContext(_localctx);
				EnterOuterAlt(_localctx, 17);
				{
				State = 220; identifier();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ProchdrContext : ParserRuleContext {
		public ProchdrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prochdr; } }
	 
		public ProchdrContext() { }
		public virtual void CopyFrom(ProchdrContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ProcheaderContext : ProchdrContext {
		public ITerminalNode DefProc() { return GetToken(SBParser.DefProc, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ParenthesizedlistContext parenthesizedlist() {
			return GetRuleContext<ParenthesizedlistContext>(0);
		}
		public ProcheaderContext(ProchdrContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterProcheader(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitProcheader(this);
		}
	}

	[RuleVersion(0)]
	public ProchdrContext prochdr() {
		ProchdrContext _localctx = new ProchdrContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_prochdr);
		int _la;
		try {
			_localctx = new ProcheaderContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 223; Match(DefProc);
			State = 224; identifier();
			State = 226;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==LeftParen) {
				{
				State = 225; parenthesizedlist();
				}
			}

			State = 228; Match(Newline);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunchdrContext : ParserRuleContext {
		public FunchdrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_funchdr; } }
	 
		public FunchdrContext() { }
		public virtual void CopyFrom(FunchdrContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FuncheaderContext : FunchdrContext {
		public ITerminalNode DefFunc() { return GetToken(SBParser.DefFunc, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode Newline() { return GetToken(SBParser.Newline, 0); }
		public ParenthesizedlistContext parenthesizedlist() {
			return GetRuleContext<ParenthesizedlistContext>(0);
		}
		public FuncheaderContext(FunchdrContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterFuncheader(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitFuncheader(this);
		}
	}

	[RuleVersion(0)]
	public FunchdrContext funchdr() {
		FunchdrContext _localctx = new FunchdrContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_funchdr);
		int _la;
		try {
			_localctx = new FuncheaderContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 230; Match(DefFunc);
			State = 231; identifier();
			State = 233;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==LeftParen) {
				{
				State = 232; parenthesizedlist();
				}
			}

			State = 235; Match(Newline);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndDefContext : ParserRuleContext {
		public ITerminalNode EndDef() { return GetToken(SBParser.EndDef, 0); }
		public EndDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_endDef; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterEndDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitEndDef(this);
		}
	}

	[RuleVersion(0)]
	public EndDefContext endDef() {
		EndDefContext _localctx = new EndDefContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_endDef);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 237; Match(EndDef);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public ParenthesizedlistContext parenthesizedlist() {
			return GetRuleContext<ParenthesizedlistContext>(0);
		}
		public UnparenthesizedlistContext unparenthesizedlist() {
			return GetRuleContext<UnparenthesizedlistContext>(0);
		}
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 239; Match(ID);
			State = 242;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,32,_ctx) ) {
			case 1:
				{
				State = 240; parenthesizedlist();
				}
				break;

			case 2:
				{
				State = 241; unparenthesizedlist();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParenthesizedlistContext : ParserRuleContext {
		public ParenthesizedlistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parenthesizedlist; } }
	 
		public ParenthesizedlistContext() { }
		public virtual void CopyFrom(ParenthesizedlistContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParenthesizedlContext : ParenthesizedlistContext {
		public ITerminalNode LeftParen() { return GetToken(SBParser.LeftParen, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode RightParen() { return GetToken(SBParser.RightParen, 0); }
		public SeparatorContext[] separator() {
			return GetRuleContexts<SeparatorContext>();
		}
		public SeparatorContext separator(int i) {
			return GetRuleContext<SeparatorContext>(i);
		}
		public ParenthesizedlContext(ParenthesizedlistContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterParenthesizedl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitParenthesizedl(this);
		}
	}

	[RuleVersion(0)]
	public ParenthesizedlistContext parenthesizedlist() {
		ParenthesizedlistContext _localctx = new ParenthesizedlistContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_parenthesizedlist);
		int _la;
		try {
			_localctx = new ParenthesizedlContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 244; Match(LeftParen);
			State = 245; expr(0);
			State = 251;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << To) | (1L << Semi) | (1L << Comma) | (1L << Bang))) != 0)) {
				{
				{
				State = 246; separator();
				State = 247; expr(0);
				}
				}
				State = 253;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 254; Match(RightParen);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnparenthesizedlistContext : ParserRuleContext {
		public UnparenthesizedlistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unparenthesizedlist; } }
	 
		public UnparenthesizedlistContext() { }
		public virtual void CopyFrom(UnparenthesizedlistContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class UnparenthesizedContext : UnparenthesizedlistContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public SeparatorContext[] separator() {
			return GetRuleContexts<SeparatorContext>();
		}
		public SeparatorContext separator(int i) {
			return GetRuleContext<SeparatorContext>(i);
		}
		public UnparenthesizedContext(UnparenthesizedlistContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterUnparenthesized(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitUnparenthesized(this);
		}
	}

	[RuleVersion(0)]
	public UnparenthesizedlistContext unparenthesizedlist() {
		UnparenthesizedlistContext _localctx = new UnparenthesizedlistContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_unparenthesizedlist);
		try {
			int _alt;
			_localctx = new UnparenthesizedContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 256; expr(0);
			State = 262;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,34,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 257; separator();
					State = 258; expr(0);
					}
					} 
				}
				State = 264;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,34,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SeparatorContext : ParserRuleContext {
		public ITerminalNode Comma() { return GetToken(SBParser.Comma, 0); }
		public ITerminalNode Bang() { return GetToken(SBParser.Bang, 0); }
		public ITerminalNode Semi() { return GetToken(SBParser.Semi, 0); }
		public ITerminalNode To() { return GetToken(SBParser.To, 0); }
		public SeparatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_separator; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterSeparator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitSeparator(this);
		}
	}

	[RuleVersion(0)]
	public SeparatorContext separator() {
		SeparatorContext _localctx = new SeparatorContext(_ctx, State);
		EnterRule(_localctx, 24, RULE_separator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 265;
			_la = _input.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << To) | (1L << Semi) | (1L << Comma) | (1L << Bang))) != 0)) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParenthesizedContext : ExprContext {
		public ITerminalNode LeftParen() { return GetToken(SBParser.LeftParen, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode RightParen() { return GetToken(SBParser.RightParen, 0); }
		public ParenthesizedContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterParenthesized(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitParenthesized(this);
		}
	}
	public partial class UnaryAdditiveContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode Plus() { return GetToken(SBParser.Plus, 0); }
		public ITerminalNode Minus() { return GetToken(SBParser.Minus, 0); }
		public UnaryAdditiveContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterUnaryAdditive(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitUnaryAdditive(this);
		}
	}
	public partial class BinaryContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode Amp() { return GetToken(SBParser.Amp, 0); }
		public ITerminalNode Caret() { return GetToken(SBParser.Caret, 0); }
		public ITerminalNode Multiply() { return GetToken(SBParser.Multiply, 0); }
		public ITerminalNode Divide() { return GetToken(SBParser.Divide, 0); }
		public ITerminalNode Mod() { return GetToken(SBParser.Mod, 0); }
		public ITerminalNode Div() { return GetToken(SBParser.Div, 0); }
		public ITerminalNode Plus() { return GetToken(SBParser.Plus, 0); }
		public ITerminalNode Minus() { return GetToken(SBParser.Minus, 0); }
		public ITerminalNode Equal() { return GetToken(SBParser.Equal, 0); }
		public ITerminalNode NotEqual() { return GetToken(SBParser.NotEqual, 0); }
		public ITerminalNode Less() { return GetToken(SBParser.Less, 0); }
		public ITerminalNode LessEqual() { return GetToken(SBParser.LessEqual, 0); }
		public ITerminalNode Greater() { return GetToken(SBParser.Greater, 0); }
		public ITerminalNode GreaterEqual() { return GetToken(SBParser.GreaterEqual, 0); }
		public ITerminalNode And() { return GetToken(SBParser.And, 0); }
		public ITerminalNode Or() { return GetToken(SBParser.Or, 0); }
		public ITerminalNode Xor() { return GetToken(SBParser.Xor, 0); }
		public BinaryContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterBinary(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitBinary(this);
		}
	}
	public partial class InstrContext : ExprContext {
		public ITerminalNode Instr() { return GetToken(SBParser.Instr, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode String() { return GetToken(SBParser.String, 0); }
		public ITerminalNode ID() { return GetToken(SBParser.ID, 0); }
		public InstrContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterInstr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitInstr(this);
		}
	}
	public partial class NotContext : ExprContext {
		public ITerminalNode Not() { return GetToken(SBParser.Not, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NotContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterNot(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitNot(this);
		}
	}
	public partial class TermContext : ExprContext {
		public TerminatorContext terminator() {
			return GetRuleContext<TerminatorContext>(0);
		}
		public TermContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterTerm(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitTerm(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(_ctx, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 26;
		EnterRecursionRule(_localctx, 26, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 280;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,35,_ctx) ) {
			case 1:
				{
				_localctx = new ParenthesizedContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;

				State = 268; Match(LeftParen);
				State = 269; expr(0);
				State = 270; Match(RightParen);
				}
				break;

			case 2:
				{
				_localctx = new UnaryAdditiveContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 272;
				_la = _input.La(1);
				if ( !(_la==Plus || _la==Minus) ) {
				_errHandler.RecoverInline(this);
				} else {
					if (_input.La(1) == TokenConstants.Eof) {
						matchedEOF = true;
					}

					_errHandler.ReportMatch(this);
					Consume();
				}
				State = 273; expr(11);
				}
				break;

			case 3:
				{
				_localctx = new InstrContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 274;
				_la = _input.La(1);
				if ( !(_la==String || _la==ID) ) {
				_errHandler.RecoverInline(this);
				} else {
					if (_input.La(1) == TokenConstants.Eof) {
						matchedEOF = true;
					}

					_errHandler.ReportMatch(this);
					Consume();
				}
				State = 275; Match(Instr);
				State = 276; expr(9);
				}
				break;

			case 4:
				{
				_localctx = new NotContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 277; Match(Not);
				State = 278; expr(4);
				}
				break;

			case 5:
				{
				_localctx = new TermContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 279; terminator();
				}
				break;
			}
			_ctx.stop = _input.Lt(-1);
			State = 305;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,37,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 303;
					_errHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(_input,36,_ctx) ) {
					case 1:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 282;
						if (!(Precpred(_ctx, 10))) throw new FailedPredicateException(this, "Precpred(_ctx, 10)");
						State = 283; Match(Amp);
						State = 284; expr(11);
						}
						break;

					case 2:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 285;
						if (!(Precpred(_ctx, 8))) throw new FailedPredicateException(this, "Precpred(_ctx, 8)");
						State = 286; Match(Caret);
						State = 287; expr(8);
						}
						break;

					case 3:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 288;
						if (!(Precpred(_ctx, 7))) throw new FailedPredicateException(this, "Precpred(_ctx, 7)");
						State = 289;
						_la = _input.La(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Multiply) | (1L << Divide) | (1L << Mod) | (1L << Div))) != 0)) ) {
						_errHandler.RecoverInline(this);
						} else {
							if (_input.La(1) == TokenConstants.Eof) {
								matchedEOF = true;
							}

							_errHandler.ReportMatch(this);
							Consume();
						}
						State = 290; expr(8);
						}
						break;

					case 4:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 291;
						if (!(Precpred(_ctx, 6))) throw new FailedPredicateException(this, "Precpred(_ctx, 6)");
						State = 292;
						_la = _input.La(1);
						if ( !(_la==Plus || _la==Minus) ) {
						_errHandler.RecoverInline(this);
						} else {
							if (_input.La(1) == TokenConstants.Eof) {
								matchedEOF = true;
							}

							_errHandler.ReportMatch(this);
							Consume();
						}
						State = 293; expr(7);
						}
						break;

					case 5:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 294;
						if (!(Precpred(_ctx, 5))) throw new FailedPredicateException(this, "Precpred(_ctx, 5)");
						State = 295;
						_la = _input.La(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Equal) | (1L << NotEqual) | (1L << Less) | (1L << LessEqual) | (1L << Greater) | (1L << GreaterEqual))) != 0)) ) {
						_errHandler.RecoverInline(this);
						} else {
							if (_input.La(1) == TokenConstants.Eof) {
								matchedEOF = true;
							}

							_errHandler.ReportMatch(this);
							Consume();
						}
						State = 296; expr(6);
						}
						break;

					case 6:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 297;
						if (!(Precpred(_ctx, 3))) throw new FailedPredicateException(this, "Precpred(_ctx, 3)");
						State = 298; Match(And);
						State = 299; expr(4);
						}
						break;

					case 7:
						{
						_localctx = new BinaryContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 300;
						if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
						State = 301;
						_la = _input.La(1);
						if ( !(_la==Or || _la==Xor) ) {
						_errHandler.RecoverInline(this);
						} else {
							if (_input.La(1) == TokenConstants.Eof) {
								matchedEOF = true;
							}

							_errHandler.ReportMatch(this);
							Consume();
						}
						State = 302; expr(3);
						}
						break;
					}
					} 
				}
				State = 307;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,37,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class TerminatorContext : ParserRuleContext {
		public ITerminalNode Integer() { return GetToken(SBParser.Integer, 0); }
		public ITerminalNode String() { return GetToken(SBParser.String, 0); }
		public ITerminalNode Real() { return GetToken(SBParser.Real, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public TerminatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_terminator; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.EnterTerminator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISBListener typedListener = listener as ISBListener;
			if (typedListener != null) typedListener.ExitTerminator(this);
		}
	}

	[RuleVersion(0)]
	public TerminatorContext terminator() {
		TerminatorContext _localctx = new TerminatorContext(_ctx, State);
		EnterRule(_localctx, 28, RULE_terminator);
		try {
			State = 312;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case Integer:
				EnterOuterAlt(_localctx, 1);
				{
				State = 308; Match(Integer);
				}
				break;
			case String:
				EnterOuterAlt(_localctx, 2);
				{
				State = 309; Match(String);
				}
				break;
			case Real:
				EnterOuterAlt(_localctx, 3);
				{
				State = 310; Match(Real);
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 4);
				{
				State = 311; identifier();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 13: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(_ctx, 10);

		case 1: return Precpred(_ctx, 8);

		case 2: return Precpred(_ctx, 7);

		case 3: return Precpred(_ctx, 6);

		case 4: return Precpred(_ctx, 5);

		case 5: return Precpred(_ctx, 3);

		case 6: return Precpred(_ctx, 2);
		}
		return true;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\x43\x13D\x4\x2"+
		"\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4"+
		"\t\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10"+
		"\t\x10\x3\x2\x6\x2\"\n\x2\r\x2\xE\x2#\x3\x2\x3\x2\x3\x3\x5\x3)\n\x3\x3"+
		"\x3\x5\x3,\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\x5\x3\x32\n\x3\x3\x4\x3\x4\x3"+
		"\x4\a\x4\x37\n\x4\f\x4\xE\x4:\v\x4\x3\x5\x3\x5\x3\x6\x3\x6\x3\x6\x3\x6"+
		"\x3\x6\x5\x6\x43\n\x6\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3"+
		"\a\x3\a\a\aP\n\a\f\a\xE\aS\v\a\x3\a\x5\aV\n\a\x3\a\x3\a\x5\aZ\n\a\x3\a"+
		"\x3\a\a\a^\n\a\f\a\xE\a\x61\v\a\x3\a\x5\a\x64\n\a\x3\a\x3\a\x5\ah\n\a"+
		"\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x5\ar\n\a\x3\a\x3\a\a\av\n\a"+
		"\f\a\xE\ay\v\a\x3\a\x5\a|\n\a\x3\a\x3\a\x5\a\x80\n\a\x3\a\x3\a\x3\a\x3"+
		"\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\a"+
		"\a\x93\n\a\f\a\xE\a\x96\v\a\x3\a\x5\a\x99\n\a\x3\a\x3\a\x5\a\x9D\n\a\x3"+
		"\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x5\a\xA7\n\a\x3\a\x3\a\x3\a\x5\a"+
		"\xAC\n\a\x3\a\x3\a\x6\a\xB0\n\a\r\a\xE\a\xB1\x3\a\x5\a\xB5\n\a\x3\a\x3"+
		"\a\x6\a\xB9\n\a\r\a\xE\a\xBA\x5\a\xBD\n\a\x3\a\x5\a\xC0\n\a\x3\a\x3\a"+
		"\x3\a\x3\a\x3\a\x3\a\a\a\xC8\n\a\f\a\xE\a\xCB\v\a\x3\a\x5\a\xCE\n\a\x3"+
		"\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x5\a\xD9\n\a\x3\a\x3\a\x3\a"+
		"\x3\a\x3\a\x5\a\xE0\n\a\x3\b\x3\b\x3\b\x5\b\xE5\n\b\x3\b\x3\b\x3\t\x3"+
		"\t\x3\t\x5\t\xEC\n\t\x3\t\x3\t\x3\n\x3\n\x3\v\x3\v\x3\v\x5\v\xF5\n\v\x3"+
		"\f\x3\f\x3\f\x3\f\x3\f\a\f\xFC\n\f\f\f\xE\f\xFF\v\f\x3\f\x3\f\x3\r\x3"+
		"\r\x3\r\x3\r\a\r\x107\n\r\f\r\xE\r\x10A\v\r\x3\xE\x3\xE\x3\xF\x3\xF\x3"+
		"\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x5\xF"+
		"\x11B\n\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF"+
		"\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\a\xF"+
		"\x132\n\xF\f\xF\xE\xF\x135\v\xF\x3\x10\x3\x10\x3\x10\x3\x10\x5\x10\x13B"+
		"\n\x10\x3\x10\x2\x2\x3\x1C\x11\x2\x2\x4\x2\x6\x2\b\x2\n\x2\f\x2\xE\x2"+
		"\x10\x2\x12\x2\x14\x2\x16\x2\x18\x2\x1A\x2\x1C\x2\x1E\x2\x2\n\x4\x2;;"+
		"=?\x4\x2\v\v\x33\x33\x5\x2\x13\x13\x34\x35\x37\x37\x3\x2$%\x4\x2;;==\x3"+
		"\x2&)\x3\x2\x1E#\x3\x2+,\x16E\x2!\x3\x2\x2\x2\x4\x31\x3\x2\x2\x2\x6\x33"+
		"\x3\x2\x2\x2\b;\x3\x2\x2\x2\n\x42\x3\x2\x2\x2\f\xDF\x3\x2\x2\x2\xE\xE1"+
		"\x3\x2\x2\x2\x10\xE8\x3\x2\x2\x2\x12\xEF\x3\x2\x2\x2\x14\xF1\x3\x2\x2"+
		"\x2\x16\xF6\x3\x2\x2\x2\x18\x102\x3\x2\x2\x2\x1A\x10B\x3\x2\x2\x2\x1C"+
		"\x11A\x3\x2\x2\x2\x1E\x13A\x3\x2\x2\x2 \"\x5\x4\x3\x2! \x3\x2\x2\x2\""+
		"#\x3\x2\x2\x2#!\x3\x2\x2\x2#$\x3\x2\x2\x2$%\x3\x2\x2\x2%&\a\x2\x2\x3&"+
		"\x3\x3\x2\x2\x2\')\a>\x2\x2(\'\x3\x2\x2\x2()\x3\x2\x2\x2)+\x3\x2\x2\x2"+
		"*,\x5\x6\x4\x2+*\x3\x2\x2\x2+,\x3\x2\x2\x2,-\x3\x2\x2\x2-\x32\a:\x2\x2"+
		"./\a>\x2\x2/\x30\a\x33\x2\x2\x30\x32\a:\x2\x2\x31(\x3\x2\x2\x2\x31.\x3"+
		"\x2\x2\x2\x32\x5\x3\x2\x2\x2\x33\x38\x5\f\a\x2\x34\x35\a\x33\x2\x2\x35"+
		"\x37\x5\f\a\x2\x36\x34\x3\x2\x2\x2\x37:\x3\x2\x2\x2\x38\x36\x3\x2\x2\x2"+
		"\x38\x39\x3\x2\x2\x2\x39\a\x3\x2\x2\x2:\x38\x3\x2\x2\x2;<\t\x2\x2\x2<"+
		"\t\x3\x2\x2\x2=>\x5\b\x5\x2>?\a\x13\x2\x2?@\x5\b\x5\x2@\x43\x3\x2\x2\x2"+
		"\x41\x43\x5\b\x5\x2\x42=\x3\x2\x2\x2\x42\x41\x3\x2\x2\x2\x43\v\x3\x2\x2"+
		"\x2\x44\x45\a\x6\x2\x2\x45\x46\a=\x2\x2\x46\xE0\x5\x16\f\x2GH\a\x5\x2"+
		"\x2H\xE0\x5\x18\r\x2IJ\a\x4\x2\x2J\xE0\x5\x18\r\x2KL\a\x3\x2\x2L\xE0\x5"+
		"\x18\r\x2MQ\x5\xE\b\x2NP\x5\x4\x3\x2ON\x3\x2\x2\x2PS\x3\x2\x2\x2QO\x3"+
		"\x2\x2\x2QR\x3\x2\x2\x2RU\x3\x2\x2\x2SQ\x3\x2\x2\x2TV\a>\x2\x2UT\x3\x2"+
		"\x2\x2UV\x3\x2\x2\x2VW\x3\x2\x2\x2WY\x5\x12\n\x2XZ\a=\x2\x2YX\x3\x2\x2"+
		"\x2YZ\x3\x2\x2\x2Z\xE0\x3\x2\x2\x2[_\x5\x10\t\x2\\^\x5\x4\x3\x2]\\\x3"+
		"\x2\x2\x2^\x61\x3\x2\x2\x2_]\x3\x2\x2\x2_`\x3\x2\x2\x2`\x63\x3\x2\x2\x2"+
		"\x61_\x3\x2\x2\x2\x62\x64\a>\x2\x2\x63\x62\x3\x2\x2\x2\x63\x64\x3\x2\x2"+
		"\x2\x64\x65\x3\x2\x2\x2\x65g\x5\x12\n\x2\x66h\a=\x2\x2g\x66\x3\x2\x2\x2"+
		"gh\x3\x2\x2\x2h\xE0\x3\x2\x2\x2ij\a\x11\x2\x2jk\a=\x2\x2kl\a\x1E\x2\x2"+
		"lm\x5\x1C\xF\x2mn\a\x13\x2\x2nq\x5\x1C\xF\x2op\a\x15\x2\x2pr\x5\x1E\x10"+
		"\x2qo\x3\x2\x2\x2qr\x3\x2\x2\x2rs\x3\x2\x2\x2sw\a:\x2\x2tv\x5\x4\x3\x2"+
		"ut\x3\x2\x2\x2vy\x3\x2\x2\x2wu\x3\x2\x2\x2wx\x3\x2\x2\x2x{\x3\x2\x2\x2"+
		"yw\x3\x2\x2\x2z|\a>\x2\x2{z\x3\x2\x2\x2{|\x3\x2\x2\x2|}\x3\x2\x2\x2}\x7F"+
		"\a\x14\x2\x2~\x80\a=\x2\x2\x7F~\x3\x2\x2\x2\x7F\x80\x3\x2\x2\x2\x80\xE0"+
		"\x3\x2\x2\x2\x81\x82\a\x11\x2\x2\x82\x83\a=\x2\x2\x83\x84\a\x1E\x2\x2"+
		"\x84\x85\x5\x1C\xF\x2\x85\x86\a\x13\x2\x2\x86\x87\x5\x1C\xF\x2\x87\x88"+
		"\a\x33\x2\x2\x88\x89\x5\x6\x4\x2\x89\xE0\x3\x2\x2\x2\x8A\x8B\a\x16\x2"+
		"\x2\x8B\x8C\a=\x2\x2\x8C\x8D\a\x33\x2\x2\x8D\xE0\x5\x6\x4\x2\x8E\x8F\a"+
		"\x16\x2\x2\x8F\x90\a=\x2\x2\x90\x94\a:\x2\x2\x91\x93\x5\x4\x3\x2\x92\x91"+
		"\x3\x2\x2\x2\x93\x96\x3\x2\x2\x2\x94\x92\x3\x2\x2\x2\x94\x95\x3\x2\x2"+
		"\x2\x95\x98\x3\x2\x2\x2\x96\x94\x3\x2\x2\x2\x97\x99\a>\x2\x2\x98\x97\x3"+
		"\x2\x2\x2\x98\x99\x3\x2\x2\x2\x99\x9A\x3\x2\x2\x2\x9A\x9C\a\x19\x2\x2"+
		"\x9B\x9D\a=\x2\x2\x9C\x9B\x3\x2\x2\x2\x9C\x9D\x3\x2\x2\x2\x9D\xE0\x3\x2"+
		"\x2\x2\x9E\x9F\a\t\x2\x2\x9F\xA0\x5\x1C\xF\x2\xA0\xA1\t\x3\x2\x2\xA1\xA6"+
		"\x5\x6\x4\x2\xA2\xA3\a\x33\x2\x2\xA3\xA4\a\n\x2\x2\xA4\xA5\a\x33\x2\x2"+
		"\xA5\xA7\x5\x6\x4\x2\xA6\xA2\x3\x2\x2\x2\xA6\xA7\x3\x2\x2\x2\xA7\xE0\x3"+
		"\x2\x2\x2\xA8\xA9\a\t\x2\x2\xA9\xAB\x5\x1C\xF\x2\xAA\xAC\a\v\x2\x2\xAB"+
		"\xAA\x3\x2\x2\x2\xAB\xAC\x3\x2\x2\x2\xAC\xAD\x3\x2\x2\x2\xAD\xAF\a:\x2"+
		"\x2\xAE\xB0\x5\x4\x3\x2\xAF\xAE\x3\x2\x2\x2\xB0\xB1\x3\x2\x2\x2\xB1\xAF"+
		"\x3\x2\x2\x2\xB1\xB2\x3\x2\x2\x2\xB2\xBC\x3\x2\x2\x2\xB3\xB5\a>\x2\x2"+
		"\xB4\xB3\x3\x2\x2\x2\xB4\xB5\x3\x2\x2\x2\xB5\xB6\x3\x2\x2\x2\xB6\xB8\a"+
		"\n\x2\x2\xB7\xB9\x5\x4\x3\x2\xB8\xB7\x3\x2\x2\x2\xB9\xBA\x3\x2\x2\x2\xBA"+
		"\xB8\x3\x2\x2\x2\xBA\xBB\x3\x2\x2\x2\xBB\xBD\x3\x2\x2\x2\xBC\xB4\x3\x2"+
		"\x2\x2\xBC\xBD\x3\x2\x2\x2\xBD\xBF\x3\x2\x2\x2\xBE\xC0\a>\x2\x2\xBF\xBE"+
		"\x3\x2\x2\x2\xBF\xC0\x3\x2\x2\x2\xC0\xC1\x3\x2\x2\x2\xC1\xC2\a\f\x2\x2"+
		"\xC2\xE0\x3\x2\x2\x2\xC3\xC4\a\r\x2\x2\xC4\xC5\x5\b\x5\x2\xC5\xC9\a:\x2"+
		"\x2\xC6\xC8\x5\x4\x3\x2\xC7\xC6\x3\x2\x2\x2\xC8\xCB\x3\x2\x2\x2\xC9\xC7"+
		"\x3\x2\x2\x2\xC9\xCA\x3\x2\x2\x2\xCA\xCD\x3\x2\x2\x2\xCB\xC9\x3\x2\x2"+
		"\x2\xCC\xCE\a>\x2\x2\xCD\xCC\x3\x2\x2\x2\xCD\xCE\x3\x2\x2\x2\xCE\xCF\x3"+
		"\x2\x2\x2\xCF\xD0\a\xE\x2\x2\xD0\xE0\x3\x2\x2\x2\xD1\xD2\a\x10\x2\x2\xD2"+
		"\xD3\x5\b\x5\x2\xD3\xD4\a\x1E\x2\x2\xD4\xD5\x5\n\x6\x2\xD5\xE0\x3\x2\x2"+
		"\x2\xD6\xD8\a\x17\x2\x2\xD7\xD9\a=\x2\x2\xD8\xD7\x3\x2\x2\x2\xD8\xD9\x3"+
		"\x2\x2\x2\xD9\xE0\x3\x2\x2\x2\xDA\xDB\x5\x14\v\x2\xDB\xDC\a\x1E\x2\x2"+
		"\xDC\xDD\x5\x1C\xF\x2\xDD\xE0\x3\x2\x2\x2\xDE\xE0\x5\x14\v\x2\xDF\x44"+
		"\x3\x2\x2\x2\xDFG\x3\x2\x2\x2\xDFI\x3\x2\x2\x2\xDFK\x3\x2\x2\x2\xDFM\x3"+
		"\x2\x2\x2\xDF[\x3\x2\x2\x2\xDFi\x3\x2\x2\x2\xDF\x81\x3\x2\x2\x2\xDF\x8A"+
		"\x3\x2\x2\x2\xDF\x8E\x3\x2\x2\x2\xDF\x9E\x3\x2\x2\x2\xDF\xA8\x3\x2\x2"+
		"\x2\xDF\xC3\x3\x2\x2\x2\xDF\xD1\x3\x2\x2\x2\xDF\xD6\x3\x2\x2\x2\xDF\xDA"+
		"\x3\x2\x2\x2\xDF\xDE\x3\x2\x2\x2\xE0\r\x3\x2\x2\x2\xE1\xE2\a\a\x2\x2\xE2"+
		"\xE4\x5\x14\v\x2\xE3\xE5\x5\x16\f\x2\xE4\xE3\x3\x2\x2\x2\xE4\xE5\x3\x2"+
		"\x2\x2\xE5\xE6\x3\x2\x2\x2\xE6\xE7\a:\x2\x2\xE7\xF\x3\x2\x2\x2\xE8\xE9"+
		"\a\b\x2\x2\xE9\xEB\x5\x14\v\x2\xEA\xEC\x5\x16\f\x2\xEB\xEA\x3\x2\x2\x2"+
		"\xEB\xEC\x3\x2\x2\x2\xEC\xED\x3\x2\x2\x2\xED\xEE\a:\x2\x2\xEE\x11\x3\x2"+
		"\x2\x2\xEF\xF0\a\xF\x2\x2\xF0\x13\x3\x2\x2\x2\xF1\xF4\a=\x2\x2\xF2\xF5"+
		"\x5\x16\f\x2\xF3\xF5\x5\x18\r\x2\xF4\xF2\x3\x2\x2\x2\xF4\xF3\x3\x2\x2"+
		"\x2\xF4\xF5\x3\x2\x2\x2\xF5\x15\x3\x2\x2\x2\xF6\xF7\a\x1A\x2\x2\xF7\xFD"+
		"\x5\x1C\xF\x2\xF8\xF9\x5\x1A\xE\x2\xF9\xFA\x5\x1C\xF\x2\xFA\xFC\x3\x2"+
		"\x2\x2\xFB\xF8\x3\x2\x2\x2\xFC\xFF\x3\x2\x2\x2\xFD\xFB\x3\x2\x2\x2\xFD"+
		"\xFE\x3\x2\x2\x2\xFE\x100\x3\x2\x2\x2\xFF\xFD\x3\x2\x2\x2\x100\x101\a"+
		"\x1B\x2\x2\x101\x17\x3\x2\x2\x2\x102\x108\x5\x1C\xF\x2\x103\x104\x5\x1A"+
		"\xE\x2\x104\x105\x5\x1C\xF\x2\x105\x107\x3\x2\x2\x2\x106\x103\x3\x2\x2"+
		"\x2\x107\x10A\x3\x2\x2\x2\x108\x106\x3\x2\x2\x2\x108\x109\x3\x2\x2\x2"+
		"\x109\x19\x3\x2\x2\x2\x10A\x108\x3\x2\x2\x2\x10B\x10C\t\x4\x2\x2\x10C"+
		"\x1B\x3\x2\x2\x2\x10D\x10E\b\xF\x1\x2\x10E\x10F\a\x1A\x2\x2\x10F\x110"+
		"\x5\x1C\xF\x2\x110\x111\a\x1B\x2\x2\x111\x11B\x3\x2\x2\x2\x112\x113\t"+
		"\x5\x2\x2\x113\x11B\x5\x1C\xF\r\x114\x115\t\x6\x2\x2\x115\x116\a\x30\x2"+
		"\x2\x116\x11B\x5\x1C\xF\v\x117\x118\a.\x2\x2\x118\x11B\x5\x1C\xF\x6\x119"+
		"\x11B\x5\x1E\x10\x2\x11A\x10D\x3\x2\x2\x2\x11A\x112\x3\x2\x2\x2\x11A\x114"+
		"\x3\x2\x2\x2\x11A\x117\x3\x2\x2\x2\x11A\x119\x3\x2\x2\x2\x11B\x133\x3"+
		"\x2\x2\x2\x11C\x11D\f\f\x2\x2\x11D\x11E\a\x31\x2\x2\x11E\x132\x5\x1C\xF"+
		"\r\x11F\x120\f\n\x2\x2\x120\x121\a-\x2\x2\x121\x132\x5\x1C\xF\n\x122\x123"+
		"\f\t\x2\x2\x123\x124\t\a\x2\x2\x124\x132\x5\x1C\xF\n\x125\x126\f\b\x2"+
		"\x2\x126\x127\t\x5\x2\x2\x127\x132\x5\x1C\xF\t\x128\x129\f\a\x2\x2\x129"+
		"\x12A\t\b\x2\x2\x12A\x132\x5\x1C\xF\b\x12B\x12C\f\x5\x2\x2\x12C\x12D\a"+
		"*\x2\x2\x12D\x132\x5\x1C\xF\x6\x12E\x12F\f\x4\x2\x2\x12F\x130\t\t\x2\x2"+
		"\x130\x132\x5\x1C\xF\x5\x131\x11C\x3\x2\x2\x2\x131\x11F\x3\x2\x2\x2\x131"+
		"\x122\x3\x2\x2\x2\x131\x125\x3\x2\x2\x2\x131\x128\x3\x2\x2\x2\x131\x12B"+
		"\x3\x2\x2\x2\x131\x12E\x3\x2\x2\x2\x132\x135\x3\x2\x2\x2\x133\x131\x3"+
		"\x2\x2\x2\x133\x134\x3\x2\x2\x2\x134\x1D\x3\x2\x2\x2\x135\x133\x3\x2\x2"+
		"\x2\x136\x13B\a>\x2\x2\x137\x13B\a;\x2\x2\x138\x13B\a?\x2\x2\x139\x13B"+
		"\x5\x14\v\x2\x13A\x136\x3\x2\x2\x2\x13A\x137\x3\x2\x2\x2\x13A\x138\x3"+
		"\x2\x2\x2\x13A\x139\x3\x2\x2\x2\x13B\x1F\x3\x2\x2\x2)#(+\x31\x38\x42Q"+
		"UY_\x63gqw{\x7F\x94\x98\x9C\xA6\xAB\xB1\xB4\xBA\xBC\xBF\xC9\xCD\xD8\xDF"+
		"\xE4\xEB\xF4\xFD\x108\x11A\x131\x133\x13A";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
