
************************************************

 avar = 9 + 3 * (4 - 1) - 5 / 6;
 var2 = -3;
string astring[,];
 astring = "hhh";
 sorts = 0;
 partitions = 0;
float a[];
float b[,,];
 shortlist = 9;
 b = a(lo);
 now = DATE;
 b = 10001;
 b = a(lo);
 sorts = 0;
 partitions = 0;
 now = DATE;
 shouldbeglobal = 104;
 a = RND(1TO10000);
 now = DATE;
 finished = DATE-now;
 i = l;
 j = r;
 pivot = b(i);
 i = i+1;
 j = j-1;
 i = i+1;
 j = j-1;
 t = this;
 this = that;
 that = t;
 p = item;
 temporary = b(p);
 b = b(p-1);
 p = p-1;
 b = temporary;
 low = bottom;
 high = top;
 ptr = bottom;
 temp = b(low);
 b = b(high);
 b = temp;
 low = low+1;
 ptr = high;
 high = high-1;
 ptr = low;
 high = high-1;
 low = low+1;
 sorts = sorts+1;
 part_elem = upper+1;
 temp = b((i+j)/2);
 k = i;
 partitions = partitions+1;
 partitions = partitions+1;
 k = k+1;
 j = j-1;
 b = b(j);
 b = temp;